### ISSUE TITLE
404 link for scoped package dependents

### ISSUE THREAD

**Issue by RyanCavanaugh** [npm/www#10]
Go to https://www.npmjs.com/package/@angular/router

Click the "and more" link in the Dependents list:

![image](https://cloud.githubusercontent.com/assets/6685088/17340582/b6877408-58a5-11e6-8a7a-73cacd2e2836.png)

this goes to

https://www.npmjs.com/browse/depended/@angular/router

which is looking for a missing wombat :cry:

**Comment by aredridel** [comment]
Thanks for the report! We're going to work on prioritizing the work to fix this.

**Comment by RyanCavanaugh** [comment]
Looks like it's fixed now

**Comment by aredridel** [comment]
Indeed! thank you!
