### ISSUE TITLE
1482962076662:www-13-west.internal.npmjs.com:6673:ix4qacnh:52902

### ISSUE THREAD

**Issue by MishUshakov** [npm/www#100]
1482962076662:www-13-west.internal.npmjs.com:6673:ix4qacnh:52902

**Comment by Charlotteis** [comment]
Hey @MishUshakov, just wondering if you had an issue you forgot to post?

Figured I'd notify you to check.

Else, this is totally closable.

🌸

**Comment by sclausen** [comment]
Maybe it's this page, if you click the button:
https://www.npmjs.com/forgot
I've also got this error:
1483124705225:www-14-west.internal.npmjs.com:1618:ix9js0r9:51801

**Comment by aredridel** [comment]
This has aged out of the logs I have easy access to (sorry!), but I strongly suspect this is CSRF protection getting mangled by your password manager if you use one. Turn that off, turn off its autofill, or remove the 'crumb' field from its saved data and try again.
