### ISSUE TITLE
Back button does not work on search page

### ISSUE THREAD

**Issue by jaens** [npm/www#101]
Repro:
* Search for something that returns multiple pages of results.
* Go to page 2. Expected URL (example): https://www.npmjs.com/search?q=javascript&page=2&ranking=optimal 
* Press back.

Expected:
* Goes back to page 1.

Actual:
* Page content stays the same, back button flickers.

Browser: Chrome v56

**Comment by jefflembeck** [comment]
Thank you for flagging this, we’re adding it to our queue

**Comment by ashleygwilliams** [comment]
we've added this to our internal bug tracker. thanks for filing with detailed repro instructions and browser info! it's super helpful. ✨ 👾
