### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by lucasvanhalst** [npm/www#102]
1483621333187:www-14-west.internal.npmjs.com:31092:ixhrf47v:61089

I cannot register a new account. After clicking 'create an account' I get an error page

**Comment by aredridel** [comment]
Let me see what I can find!

**Comment by aredridel** [comment]
Ah, this is an error by CSRF protection being broken, probably by a password manager you're using. If the saved form in your password manager includes a 'crumb' field, delete that.

**Comment by lucasvanhalst** [comment]
Well it was on my work pc which doesn't have a password manager, but I just registered a new account on my pc at home, which does have a password manager and strangely enough it worked. So I don't think that is the issue. I've also tried registering in incognito at work (so no extensions at all) and it also didn't work. Using chrome on ubuntu 16.04 if that helps.

**Comment by aredridel** [comment]
Interesting.

**Comment by aredridel** [comment]
We'll have to find reproduction steps for this -- the more detail you can give the better, but I will also try.

**Comment by ashleygwilliams** [comment]
@lucasvanhalst were you able to get any more detail on this issue?

**Comment by lucasvanhalst** [comment]
@ashleygwilliams no as I don't have a need for more than one npm account :) I wouldn't worry about it, something was probably messed up on my laptop..

**Comment by ashleygwilliams** [comment]
ok! well sorry you ran into this, and don't hesitate to reach out again! happy npm-ing! 📦 ✨
