### ISSUE TITLE
Markdown: Headline syntax ignored

### ISSUE THREAD

**Issue by mk-pmb** [npm/www#103]
In my `README.md`, three number signs (`###`) used to start a headline, and it [still works on Github](https://github.com/mk-pmb/rxu-js), but today it [broke on npmjs.com](https://www.npmjs.com/package/rxu). There it shows as just a regular paragraph that has number signs as its first word.

**Comment by jefflembeck** [comment]
Hey @mk-pmb,

This is an issue with https://github.com/npm/marky-markdown, so I've created one over there for you.

Thanks for flagging this!
