### ISSUE TITLE
Feature request - link to package.json?

### ISSUE THREAD

**Issue by chrisjlee** [npm/www#104]
Not sure if this already exists.

Would like to see a link to the package.json listed on each package after searching. Although it provides a decent job providing what deps / and dev deps are available, it would be nice to know what versions are needed when searching.

**Comment by jefflembeck** [comment]
@chrisjlee so we don't have something just like this at this point, but we _do_ have a link to the repo itself, which should help you with seeing the `package.json`s available on Github (you totally might have seen this already).

![hapi-stateless-notifications 2017-01-13 10-55-17](https://cloud.githubusercontent.com/assets/109699/21941688/d48b7530-d97e-11e6-92b0-5b7cd96bbda7.png)

That might not give you a solid package.json for the `latest` current version on npm, though! So this is a great idea that we'll pass on to our product team.
