### ISSUE TITLE
Inconsistent data on package page

### ISSUE THREAD

**Issue by gonzoyumo** [npm/www#106]
Hi,
I was doing some tests with a dummy package I created. When releasing new versions using `npm publish` command I see inconsistent data on the package page.

When I refresh the page, I sometimes get old or fresh data, see below:

![inconsistent_rendering](https://cloud.githubusercontent.com/assets/52993/21876142/87c2c9e6-d84e-11e6-976b-51c36e1cf88f.gif)

From: https://www.npmjs.com/package/gnz

Maybe a cache issue ?

BTW the registry seems to be consistent and always returning up to date data: https://registry.npmjs.org/gnz

Thx.

**Comment by aredridel** [comment]
We're investigating this! It looks like the internal service we use to index these may have gone out of sync.

**Comment by gonzoyumo** [comment]
Ok good luck :)
FYI we encountered a similar issue with load balanced cache instances. Only one instance (the one choosen by the lb) received the cache invalidation command, thus making the following get queries randomly returning outdated or fresh data.

**Comment by gmetzker** [comment]
I seem to be getting similar behavior.  I have publish a new version with `npm publish --tag latest`.  On my profile I can see the new version (as well as with `npm view`).  But on the package page it shows the wrong version, and the readme content hasn't updated.

**Comment by bcoe** [comment]
@gmetzker @gonzoyumo we have cache that is no longer required, but is interfering with the results shown post-publish; I'm hoping to fix this in the upcoming week.

@gmetzker you should see your results stop exhibiting this behavior after a few hours.

**Comment by gmetzker** [comment]
@bcoe Yes it look like it updated later last night.
Thanks all!
