### ISSUE TITLE
Missing head shadow on third person on home page

### ISSUE THREAD

**Issue by jefflembeck** [npm/www#108]
![npm - private browsing 2017-01-12 11-59-10](https://cloud.githubusercontent.com/assets/109699/21906082/ac44c1dc-d8be-11e6-990a-386c06b13da6.png)

**Comment by jefflembeck** [comment]
This was found due to the immense eye of one of our users!

It's pretty low priority right now, as the asset is not an easy one, but I love that attention to detail.

**Comment by ashleygwilliams** [comment]
thanks so much for filing! :shark:
