### ISSUE TITLE
Markdown: respect GitHub default branch

### ISSUE THREAD

**Issue by kravets-levko** [npm/www#109]
GitHub allows to use relative URLs in README.md; when publishing package to NPM - they become relative to the master branch (https://github.com/kravets-levko/pretty-file-icons/blob/master/index.json) - but there may be no `master` branch in the repo. I think, it should be better to resolve relative URLs using repo's default branch (in the example - `gh-pages`).

**Comment by jefflembeck** [comment]
@kravets-levko this is actually in the works right now! Should be coming down the pipeline very soon. Thank you!
