### ISSUE TITLE
README.md not displayed in recently-published scoped packages

### ISSUE THREAD

**Issue by RyanCavanaugh** [npm/www#11]
Broken: https://www.npmjs.com/package/@types/jquery
![image](https://cloud.githubusercontent.com/assets/6685088/17340334/8f3242b2-58a4-11e6-8477-1f7bcd06a0e7.png)

-----

Works: https://www.npmjs.com/package/@types/jqrangeslider
![image](https://cloud.githubusercontent.com/assets/6685088/17340348/9a8ebee2-58a4-11e6-9b20-65ca60d93abf.png)

Both of these packages have a README.md; the only difference seems to be that anything we recently published isn't displaying its README properly.

**Comment by RyanCavanaugh** [comment]
We're directing people to these package pages and it makes us look super-broken. Is there any workaround?

**Comment by chrisdickinson** [comment]
@RyanCavanaugh The couch package document appears to point at the correct `README.md` filename (via `readmeFilename`), however the `"readme"` key in the couch package document points at an empty string. That key is populated by the CLI on publish, and used by the website to display readme data — when it's missing we display the above error. I'm looking through the readme processing logs now and I don't see any errors importing the package document, which leads me to suspect that the data wasn't added by the CLI during publish. Are you using `npm publish` to publish this package?

**Comment by RyanCavanaugh** [comment]
@chrisdickinson  No, we've switched to using the API.

/cc @andy-ms

**Comment by RyanCavanaugh** [comment]
So it sounds like we need to read the `README.md` contents and put it into the `readme` key during our API-based publish? It's super surprising to me that these things work differently but it sounds like an easy fix on our end.

**Comment by jefflembeck** [comment]
Closing. Thanks for answering, @chrisdickinson !

**Comment by chrisdickinson** [comment]
@RyanCavanaugh Yep! Apologies for the surprise. Our goal is to start providing documentation for the existing registry API on the [registry repo](https://github.com/npm/registry), but it's a work in progress!

**Comment by andy-ms** [comment]
Hi, it's us again!

Some packages are not showing the latest data available. For example, [d3](https://www.npmjs.com/package/@types/d3) says that "0.0.33 is the latest of 15 releases", but actually 3.5.34 was published yesterday and is the latest of 16 releases. (Also, the readme contents are old.)

Here's the background: we are directly using the [publish](https://github.com/npm/npm-registry-client#clientpublishuri-params-cb) method from `npm-registry-client`.
Currently we use a very simple [technique](https://github.com/Microsoft/types-publisher/blob/master/src/lib/npm-client.ts#L35) to get the metadata: we read in the contents of README.md and attach it to the `package.json`.

I suspect that we are still not providing all of the metadata needed. Is there something else we need to be doing there?

(The new issue is Microsoft/types-publisher#140.)

**Comment by RyanCavanaugh** [comment]
@andy-ms can you log a new issue? Seems this isn't getting any visibility

**Comment by andy-ms** [comment]
@RyanCavanaugh #34
