### ISSUE TITLE
Trying so send a support message via npmjs.com failed

### ISSUE THREAD

**Issue by 00SteinsGate00** [npm/www#111]
I was trying to send a message with the support form on npmjs.com. But when I clicked on submit an error occurred and it said, I should contact you with the following unique code.

1484630930898:www-14-west.internal.npmjs.com:23722:ixtcf6ud:93115

Hope I could help somehow. Let me know if further information is required.

**Comment by jefflembeck** [comment]
@00SteinsGate00 I'm so sorry this happened!

Thank you for sharing this code with us and sorry I'm slow to get back to you. Were you able to contact our support team? If not, support@npmjs.com is how to get to them. Please reach out.

**Comment by 00SteinsGate00** [comment]
Don't worry :) I can image it is hard to maintain an open source project of this scale. I will reach out to that E-Mail Adress.

Thank you very much :)
