### ISSUE TITLE
Web UI does not reflect latest

### ISSUE THREAD

**Issue by hippee-lee** [npm/www#113]
If I run `npm view clarity-ui` the latest version is listed as 0.8.3. 

![screen shot 2017-01-20 at 9 07 37 am](https://cloud.githubusercontent.com/assets/433692/22158209/0420c7f2-def0-11e6-992a-221e07ab6403.png)

When I view the [clarity-ui](https://www.npmjs.com/package/clarity-ui) package on npmjs.com it still shows 0.8.2

![screen shot 2017-01-20 at 9 09 19 am](https://cloud.githubusercontent.com/assets/433692/22158245/3e61616a-def0-11e6-8b77-0b1912e18712.png)

When I run `npm install clarity-ui` version 0.8.3 gets installed and thats what I would expect if publishing was successful. 

Short of publishing a patch version is there anything I can do to bring the web-ui into parity with the repository?

**Comment by bcoe** [comment]
@hippee-lee this issue should now be resolved; we're in the process of replacing the part of the system that occasionally misses updating the UI on a publication.

**Comment by hippee-lee** [comment]
Thanks @bcoe - 0.8.3 is now showing for clarity-ui.

I'm also having the same ui issue for: 
clarity-angular and clarity-icons -> should I open a new issue?

**Comment by bcoe** [comment]
@hippee-lee out of curiosity, do you do anything interesting in your publication flow; e.g., first release to a dist-tag, then promote to latest? Interesting that you got bit on several of your packages.

To correct the issue I'm simply clicking the star icon on the given modules, which forces a re-index on the backend.

My top-priority ops work is fixing this part of the system currently, so don't worry this nuisance will be gone soon.

**Comment by hippee-lee** [comment]
@bcoe - thank you for your help / attention. It looks like the re-indexing is working, clarity-angular is now 0.8.3.

As far as anything interesting with our publication flow, no I don't think so. The files to be published are generated into a dist/npm folder, one for each the three packages: 
```
dist/npm/clarity-angular/*
dist/npm/clarity-icons/*
dist/npm/clarity-ui/*
```

Then we have a package script called publsih:all (`npm run publish:all`) that runs
``` publish:all": "npm publish dist/npm/clarity-ui; npm publish dist/npm/clarity-angular; npm publish dist/npm/clarity-icons", ```

If it helps, publish command is also here: https://github.com/vmware/clarity/blob/master/package.json
and here for the npm file prep task: https://github.com/vmware/clarity/blob/master/build/tasks/publish.js

Thanks again for your help.

**Comment by bcoe** [comment]
@hippee-lee no worries, thanks for your patience -- this just continues to motivate me to get this part of the system rebuilt ASAP.
