### ISSUE TITLE
websites crashes after I pay for private modules

### ISSUE THREAD

**Issue by tjwebb** [npm/www#114]
This is the error Id: `1485030097986:www-13-west.internal.npmjs.com:10855:iy3eb07y:78430`. I pay $7.00, but then I am logged out, and upon logging back in I still do not have private module access.

I've tried this 3 or 4 times now.

**Comment by tjwebb** [comment]
This is still happening. I can publish private modules, but I cannot npm install them, or view them on the website.

**Comment by jefflembeck** [comment]
@tjwebb SO SO Sorry to hear about this.

I'm forwarding this on to support and figuring this out from the website end right now. Can you also email support at support@npmjs.com ? We can continue the conversation there a little more easily.

**Comment by tjwebb** [comment]
will do.

As of now, I can npm install the private modules I publish, but I still cannot see them on the website.

**Comment by jefflembeck** [comment]
@tjwebb were you able to talk with our support team? I really want to make sure this gets solved for you.

**Comment by ashleygwilliams** [comment]
hey @tjwebb it's been about a month since you responded. i hope you were able to sort out this issue! please reply if you are still having trouble! closing for now.

**Comment by tjwebb** [comment]
Hey Ashley, sorry for the delay. I still get a similar error, but I am now able to access my private modules somehow.
