### ISSUE TITLE
Let's do something regarding libraries with unfriendly license types

### ISSUE THREAD

**Issue by revelt** [npm/www#115]
Currently, npm package pages don't differentiate, is the library open source or not. For example, popular package [1stdibs/gulp-sass-json](https://www.npmjs.com/package/gulp-sass-json) is not open source (it's set to "1stdibs" in particular case), yet it is not possible to find out without going to [GitHub repo](https://github.com/1stdibs/gulp-sass-json) and checking its `package.json`.

I believe the npm package **single pages** should alert the visitor if the package's license is anything else than "MIT" or "ISC".

Equally, **search results** should penalise non-MIT/non-ISC licensed libraries in the search listings, plus mark the listing entries accordingly.

I propose not to punish "GPL" in the search listings, but still, alert the user that derivatives will need to be GPL-licensed too.

License fields _GPL/LGPL_ should equally cause alert because they are [not suitable for commercial reuse](https://www.nczonline.net/blog/2015/12/why-im-not-using-your-open-source-project/).

Currently, npm is indirectly encouraging the breaking of a copyright law by not declaring the license type within single page listings.

**Comment by jefflembeck** [comment]
@revelt Coincidentally, our product team is currently figuring out ways to handle this exact situation and I've sent this along to them as more input.

Thanks so much for the request; these really help.

**Comment by isaacs** [comment]
I like the idea of calling out (but not penalizing) strong copyleft licenses and others that might pose a problem for commercial applications.  (I'd put Apache2, Artistic-2.0, WTFPL2, and BSD-2/3-clause on the list of friendlies along with ISC and MIT.  Probably it'd be worth looping in our lawyer who knows a lot more about this stuff than I do.)

I think we do need to raise a somewhat noisier warning (and perhaps penalize in search results) for any license that isn't an OSI-approved and SPDX-compliant.
