### ISSUE TITLE
Markdown: Add support for <details> / <summary> html5 tags

### ISSUE THREAD

**Issue by rundef** [npm/www#116]
GitHub support the HTML5 `<details>` tag, as you can see [here](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
But it seems like they are just stripped from the Markdown on npm's website

**Comment by jefflembeck** [comment]
Hi @rundef,

I've created an issue for this for our markdown parser. https://github.com/npm/marky-markdown/issues/332

Thank you!
