### ISSUE TITLE
contents of tables centered in README markdown

### ISSUE THREAD

**Issue by bcoe** [npm/www#118]
We have a CSS rule that is carrying from elsewhere in our style-sheets, causing tables to be rendered with their second row centered:

<img width="762" alt="screen shot 2017-01-30 at 10 37 30 am" src="https://cloud.githubusercontent.com/assets/194609/22436229/1f81380c-e6d8-11e6-9354-e6d65a9944c8.png">

This looks pretty ugly, and would be nice to fix, CC: @iarna who reported this.

**Comment by iarna** [comment]
Not just the centering but also all of the whitespace. Contrast the table as [Github renders it](https://github.com/iarna/aproba) with how [npm renders it](https://npmjs.com/package/aproba).

**Comment by gabra** [comment]
I'll look into a solution for this, it looks veeery weird!
