### ISSUE TITLE
Relative images not shown

### ISSUE THREAD

**Issue by DiegoRBaquero** [npm/www#119]
From the discussion in [uWebSockets#378](https://github.com/uWebSockets/uWebSockets/pull/378), images with relative path that are hosted in github are not shown.

The code in README.md:
```html
<div align="center"><img src="images/logo.png"/></div>
```

On GitHub:
![](https://www.dropbox.com/s/szuqbrw0lkgqjdq/Screenshot%202017-01-31%2015.26.45.jpg?dl=1)

On npmjs website:
![](https://www.dropbox.com/s/o4pt0qppaha8lpo/Screenshot%202017-01-31%2015.24.54.jpg?dl=1)

Would really like more info. Is this intended? A bug?

**Comment by ashleygwilliams** [comment]
hi! sorry you are running into this issue. this is an issue with our markdown parser marky-markdown. a relevant issue is https://github.com/npm/marky-markdown/issues/320. if you use an absolute URL to the github hosted image you can fix this right away. additionally, if you write the image using markdown and the relative link it will also work!
