### ISSUE TITLE
Wanted to use "support", got error - now i'm here

### ISSUE THREAD

**Issue by rvetere** [npm/www#120]
i just got "whoops something went wrong" after i tried to submit the support form on npmjs.com 😢 

too bad as i need really support to remove two packages because i can't make them public anymore 😭 

i got this unique error number what i wanted to put here:

```
1486033181177:www-13-west.internal.npmjs.com:4297:iyg941ni:91057
```

Can i reach somehow the support team here to help me removing "auth-box" and "auth-express" from the npmjs servers? thanks a lot!

**Comment by jefflembeck** [comment]
Hey @rvetere,

I'm very sorry to hear about this. Please reach out to support@npmjs.com and they'll take care of you (quickly, they're really amazing).

**Comment by jefflembeck** [comment]
@rvetere I hope that you were able to discuss this with support. I'm going to close this. Thanks!
