### ISSUE TITLE
HTML from README.md breaks layout of add contributor page of private packages

### ISSUE THREAD

**Issue by Jeromche** [npm/www#123]
While experimenting with private packages I experienced this problem.

To reproduce:

1. Create a private package of (in my case) a create-react-app.
2. Click the plus icon to add a contributor.
3. The layout is broken.

**Comment by ashleygwilliams** [comment]
hey! i've def experienced this. we've already got this filed in our internal issue tracker! thanks for reporting, we super appreciate it ✨ 🐶 💜
