### ISSUE TITLE
Strange margin on whitespace-based code blocks in README

### ISSUE THREAD

**Issue by marcbachmann** [npm/www#124]
![image](https://cloud.githubusercontent.com/assets/431376/22776812/62aeeb70-eeb1-11e6-885e-dc93d93ffd40.png)

Here's the page & readme with the issue:
https://www.npmjs.com/package/mime
https://raw.githubusercontent.com/broofa/node-mime/master/README.md

**Comment by revin** [comment]
This looks like a CSS issue? I'm seeing a 215px bottom margin on `pre code`

<img width="366" alt="screen shot showing the CSS in browser dev tools" src="https://cloud.githubusercontent.com/assets/94850/22837257/97c448b4-ef74-11e6-8172-a7f1815e088a.png">

**Comment by revin** [comment]
Update: I was working too quickly and didn't realize this was a different package than the one reported on marky-markdown; the [bitcar](https://www.npmjs.com/package/bitcar) package was also dealing with the same thing (the author has since changed the markdown so it doesn't hit this issue).

**Comment by bwrrp** [comment]
Seeing the same thing here, however, it appears the margin is 215px on some page loads and 15px on others.

**Comment by marcbachmann** [comment]
Maybe I wasn't explicit enough. I guess that's consistent.

```
Backtick-based code block.
``` 
This ends up with correct margin.
``` 

White-space based code block:

    
    This ends up with wrong margin.
    
```

**Comment by ashleygwilliams** [comment]
@revin did you confirm this is a marky issue? if so i'll close this out. if not lemme know so i can file on the npm website repo!

thanks for reporting and investigating ya'll! 🐬 👾 👻

**Comment by revin** [comment]
@ashleygwilliams it's the other way around; the web site CSS adds a margin to code blocks that weren't rendered with syntax highlighting. Marky's output matches what GitHub generates for the four-space-indented code (namely, `<pre><code> ... </code></pre>`)

**Comment by ashleygwilliams** [comment]
💯 roger, @revin, i'll add this to the internal tracker! thanks ya'll.

**Comment by ashleygwilliams** [comment]
actually @marcbachmann @bwrrp are you still seeing this issue? we landed a fix 8 days ago for this so in theory we've fixed it. lemme know if we haven't and i'll reopen!

**Comment by revin** [comment]
<img width="176" alt="screen shot 2017-02-22 at 10 35 51 am" src="https://cloud.githubusercontent.com/assets/94850/23226533/ba91f8bc-f8ea-11e6-9370-bd321200533f.png">

Yeah looks fixed to me. `15px` down from `215px`.

**Comment by ashleygwilliams** [comment]
cool. i also just realized that we turned a canary off a few days ago so the behavior across refreshes should be consistent. thanks again ya'll!

**Comment by bwrrp** [comment]
I'm not getting any 215px margins anymore either. Looks like this is fixed.
