### ISSUE TITLE
Submitting the password reset form with no new password results in an error

### ISSUE THREAD

**Issue by iczero** [npm/www#125]
When attempting to reset my password, I typed my old password but submitted the form without a new password. The following error occurred:
`1487052272148:www-15-west.internal.npmjs.com:31430:iz4ygb9r:22459`

**Comment by ashleygwilliams** [comment]
hi! we've filed this on our internal bug tracker. that is def not a user friendly error! were you able to go back and successfully reset your password? if not, please contact support@npmjs.com! thanks for filing, we super appreciate it! 💟
