### ISSUE TITLE
issue A: npmjs.com shows raw HTML on "readme and info/access" page

### ISSUE THREAD

**Issue by alundiak** [npm/www#127]
Not sure if it's related to npm/www because of (https://github.com/npm/www/issues/34) or to npm/registry because of (https://github.com/npm/registry/issues/42).

but, I've recently created test project, with default empty README.md file. 
```
# test
```
Note: at that time, my repo had name "test".

And when I published module, I went to npmjs.com and looked to **"Collaborators List Edit"** (https://www.npmjs.com/package/feby/access) page where "readme and info" and "access", but I spotted on such UI:

<img width="1435" alt="npmjscom_first_view" src="https://cloud.githubusercontent.com/assets/2131633/23320870/db30b8da-fadc-11e6-9234-b61f7da4f927.png">

But later, when I published new release, with changed readme with changed content, I saw (and u may see now) as updated: https://github.com/alundiak/feby (yes - before it was /test).
Changed content:
```
+# Feby
+
+Test prj for play with NPM Registry
```

**Comment by ashleygwilliams** [comment]
ok! i have reproduced these results. i'm not entirely sure why this is happening but i have filed it on our internal issue tracker. thank you so much for filing!

**Comment by ashleygwilliams** [comment]
fyi, @alundiak  as a follow up i've also identified a separate bug and filed it on marky-markdown, if you'd like to follow that
