### ISSUE TITLE
How to get all npm modules name?

### ISSUE THREAD

**Issue by johnnyguan** [npm/www#129]
I want to get all npm modules name.then I can download them.Because we work offline,sometimes it's not inconvenient to download package then send to offline computer.

**Comment by ashleygwilliams** [comment]
hi! it sounds like you want to replicate the npm registry. this is an issue for the registry repo: https://github.com/npm/registry. i've cross posted your issue there and will give you several options!

you can follow that issue here: https://github.com/npm/registry/issues/136
