### ISSUE TITLE
stats bug

### ISSUE THREAD

**Issue by acatl** [npm/www#132]
Same stats are showing up in two diff repos: 

https://www.npmjs.com/package/JSONPath
https://www.npmjs.com/package/jsonpath

Stats
3,145 downloads in the last day
21,992 downloads in the last week
88,269 downloads in the last month

**Comment by jefflembeck** [comment]
Hi @acatl,

This is an unfortunate, but known issue. We're still figuring out a sustainable way to resolve it.

Thank you for taking the time to file this. I've made sure this is referenced in our internal bug tracker.
