### ISSUE TITLE
No stats for our scoped modules

### ISSUE THREAD

**Issue by guerricm** [npm/www#134]
We publish two modules :
https://www.npmjs.com/package/@deja-js/component
https://www.npmjs.com/package/@deja-js/resources
but no stats appear for these.

Do we have to activate something in particular ?

**Comment by jefflembeck** [comment]
@guerricm thank you for filing this.

This is an unfortunate, but known bug. We have a plan in place to fix it that we're working on right now and _hopefully_ will be out relatively soon. Sorry until then, I know it's a hassle. I've made sure to reference this in our internal bug tracker.
