### ISSUE TITLE
Typos on the docs sites

### ISSUE THREAD

**Issue by piperchester** [npm/www#135]
I see some typos on this page: https://docs.npmjs.com/getting-started/what-is-npm - most notably not capitalizing the 'S' in 'Javascript.' 

Is the website source open? Can you point me to the correct repo so I can contribute this change?

**Comment by ashleygwilliams** [comment]
hi! the docs site is open source! https://github.com/npm/docs. PRs are super welcome :) i've taken the liberty of moving this issue over there => https://github.com/npm/docs/issues/803

closing here! thanks for filing

**Comment by piperchester** [comment]
Thanks @ashleygwilliams !
