### ISSUE TITLE
Package description disappeared from package page header

### ISSUE THREAD

**Issue by samme** [npm/www#138]
It had looked like this: 

![npm](https://cloud.githubusercontent.com/assets/435681/23879915/67c70df2-080d-11e7-8db4-bddf46a9af5f.png)

**Comment by jefflembeck** [comment]
@samme hi, this is actually intentional! The descriptions were a bit of a distraction on most pages and were not intended by quite a few more (as people tended to expect our READMEs to look very similar to Github's.

Thanks for noticing the change and filing!
