### ISSUE TITLE
scoped package doesn't display stats

### ISSUE THREAD

**Issue by robertkowalski** [npm/www#139]
Hello from Cyprus npm team!

It seems that scoped packages doesn't have stats displayed on the website.

@magnolia/cli has an empty stats section:

![screen shot 2017-03-14 at 11 28 02](https://cloud.githubusercontent.com/assets/298166/23894042/5a3cdb8e-08a9-11e7-963b-7f1b054a4ce9.png)

https://www.npmjs.com/package/@magnolia/cli

turns out this happens for more scoped packages: https://www.npmjs.com/package/@angular/animation

unscoped packages are not affected, I tested with `osenv`

Question: what is the API url again to get the stats as JSON anyway?

**Comment by jefflembeck** [comment]
Unfortunately, this is a known issue (scoped packages not having stats) that we have an internal issue opened for and that we'll be getting a fix out for soonish. Thank you for flagging it.

As for the API url, https://github.com/npm/download-counts should help.
