### ISSUE TITLE
dont count 404s as downloads on non-existent modules

### ISSUE THREAD

**Issue by noformnocontent** [npm/www#142]
https://www.npmjs.com/package/sever

i created this module b/c apparently someone wrote `sever` instead of `seRver` in some script, but it was 404 all that time, and now it came with statusCode:200 and npm counted all those 404s as downloads?..

![screen shot 2017-03-19 at 16 10 59](https://cloud.githubusercontent.com/assets/23745012/24083201/5d0091d4-0cd3-11e7-90b2-954f7b93152b.png)

**Comment by noformnocontent** [comment]
author removed the module so i guess the issue is closed.

**Comment by ashleygwilliams** [comment]
thanks for reporting this! i've refiled on the npm/download-counts repo where that code exists. we'll take a look at what's happening there! thank you for filing ❤️ ⭐️

**Comment by noformnocontent** [comment]
@ashleygwilliams i dont think @seldo got the point in @npm/download-counts#30

> package made _this_ week.
> it had 38.834 downloads _the moment_ it was uploaded.
