### ISSUE TITLE
Dependents list contains packages that 404

### ISSUE THREAD

**Issue by avoidwork** [npm/www#144]
Hi,

I noticed this morning that filesize (https://www.npmjs.com/package/filesize) has a dependent named newman-kore (https://www.npmjs.com/package/newman-kore) which 404s in your web interface.

![screen shot 2017-03-22 at 9 28 02 am](https://cloud.githubusercontent.com/assets/369698/24199966/de63819a-0ee1-11e7-9d35-094c871ee797.png)

![screen shot 2017-03-22 at 9 28 05 am](https://cloud.githubusercontent.com/assets/369698/24199970/e081b564-0ee1-11e7-9beb-dcd168787e8c.png)

**Comment by soldair** [comment]
looks like newman-core was created and 20 minutes later unpublished.
`curl https://registry.npmjs.org/newman-kore | json_pp`

I expect that it takes a bit of time to update the cache of this list but we'll have to make sure there isnt an edge case that orphans the name of an unpublished package in the deps list. thank you for reporting =)

**Comment by ashleygwilliams** [comment]
we've added this to our internal issue tracker! thanks for reporting 🐶 🐬 ✨
