### ISSUE TITLE
Error while trying to add existing packages to a newly created org

### ISSUE THREAD

**Issue by n1k0** [npm/www#145]
I've just created an org and got this message after trying to add existing packages to the org. 

Error code: `1490310911919:www-13-west.internal.npmjs.com:7526:j0mvyju7:20778`

**Comment by jefflembeck** [comment]
Hi @n1k0!

Do you mind me asking what your username, the package, and the org are?

**Comment by n1k0** [comment]
Sure!

username: n1k0
orgname: kinto
packages: kinto, kinto-http

Note that I tried to associate previously existing packages with the
default unique team for this org.

Le 24 mars 2017 12:26 AM, "Jeff Lembeck" <notifications@github.com> a
écrit :

**Comment by jefflembeck** [comment]
@n1k0 I've gone ahead and added them manually, I'm looking into why you would've had this problem in the first place, but hopefully that helps you out for now!

**Comment by n1k0** [comment]
Thanks!
