### ISSUE TITLE
Dependent count does not match number of Dependents

### ISSUE THREAD

**Issue by timhurkmans** [npm/www#147]
Go to https://www.npmjs.com/package/querystringify
You will see in the bottom right Dependents (21).
Click on 'Dependents (21)' or 'and more'.
Result: It shows 15 dependents instead of 21.

So either,

Dependents (21) should be Dependents (15).

or,

It should show 21 dependents instead of 15.

(Random) other examples:
https://www.npmjs.com/package/basic-logger - Dependents (5) - Shown 4
https://www.npmjs.com/package/tsify - Dependents (43) - Shown 36
https://www.npmjs.com/browse/os - Dependents (75) - Shown 62

**Comment by ashleygwilliams** [comment]
thanks for filing this. i've added it to our internal issue tracker! ⭐️

**Comment by chocolateboy** [comment]
This is still an issue e.g. [is-observable](https://www.npmjs.com/package/is-observable) currently counts 34 dependents but only lists 28.
