### ISSUE TITLE
An error on "Create an organization"

### ISSUE THREAD

**Issue by vchimev** [npm/www#148]
I tried to create a new organization named "ns".

Unique error number: 1490357307440:www-15-west.internal.npmjs.com:22337:j0mvz8u3:89984

**Comment by jefflembeck** [comment]
@vchimev if you don't mind me asking,

Were you creating a new org from scratch or transferring the username `ns`?

**Comment by vchimev** [comment]
@jefflembeck, I were creating a new org from scratch.

**Comment by ashleygwilliams** [comment]
have you tried again since, @vchimev ? does it work for you now by any chance?

**Comment by andrewprofile** [comment]
Today, not working too

**Comment by ashleygwilliams** [comment]
@andrewprofile can you give me the steps to reproduce and the error you get?

**Comment by andrewprofile** [comment]
I choose a free plain for new organization and tried create with name alpine-stack.

**Comment by vchimev** [comment]
@ashleygwilliams, @jefflembeck,

I just tried to create a new organization named "ns" again. This time I didn't get unique error number, but error message: `The provided Org's @scope name is already in use`.

**Comment by jefflembeck** [comment]
@vchimev that part is actually true so that error is valid.

There is a user named `ns` -> https://www.npmjs.com/~ns

If that's your user, you can convert that namespace to an org.

**Comment by bentruyman** [comment]
I tried something similar today (using the scope "truyman") and received the same "The provided Org's @scope name is already in use" error. I tried this with both the paid and free plans. I did this while logged in as "bentruyman". And I can't see any packages, orgs, or users that currently use that name.

Are we doing something wrong?

**Comment by bentruyman** [comment]
Disregard my last message. After looking again, I can see the org was actually created despite never getting any sort of success page or other confirmation (e.g. email). Not sure what was going on, but it created it.

FWIW, I first tried a name which _was_ taken, received the "scope already exists error", then tried another, "truyman", which wasn't taken, and received the same error. But it must have actually created it.

**Comment by jefflembeck** [comment]
@bentruyman thanks for reporting that. That sounds like one heck of a weird bug. I'm sorry it happened to ya.

We're trying to get to the bottom of why this happens when it happens. Thanks for your patience.

**Comment by vchimev** [comment]
Thanks, @jefflembeck!
