### ISSUE TITLE
Most of the packages I've published don't appear on organization "add packages"

### ISSUE THREAD

**Issue by amb26** [npm/www#149]
I only have the option to add a small number of packages to the organisation I've created. As my profile shows https://www.npmjs.com/~amb26 I have published 28 packages, but only 9 of these appear as available to add to any organisation that I create.

**Comment by ashleygwilliams** [comment]
hi! we've added this to our internal tracker and are currently working to fix this behavior and make it clearer. thank you for filing! ⭐️ ✨
