### ISSUE TITLE
My package can not find on the website

### ISSUE THREAD

**Issue by masquevil** [npm/www#150]
I published a package named "ether-vway".
When I search my package, I can find the result in the search page: https://www.npmjs.com/search?q=vway .
But when I click the package name go into the detail page, it is a not found page: https://www.npmjs.com/package/ether-vway .
Also When I go to my profile page, it shows I have 0 packages.

It's very confused for me.
Thank you very mush for helping!

**Comment by bcoe** [comment]
@masquevil it looks like there was a bug where the package was deleted from part of our system, but not another; this was causing issues when you republished.

Mind looking at the page now, and making sure everything looks correct? I also recommend publishing a patch release, to make sure you have appropriate permissions.

**Comment by masquevil** [comment]
Thank you very much for helping! I think everything is correct now

**Comment by bcoe** [comment]
@masquevil awesome, sorry about that!
