### ISSUE TITLE
Autofocus on the search field on npmjs.com

### ISSUE THREAD

**Issue by googol7** [npm/www#151]
It would be nice if the search field on npmjs.com would have the input focus so that I can immediately start typing without having to select the field first.

`<input name="q" value="" type="search" id="site-search" placeholder="find packages" tabindex="1" autocorrect="off" autocapitalize="off" itemprop="query-input" autocomplete="off">`

**Comment by ashleygwilliams** [comment]
hi! it turns out doing this is really tough on screen readers! i understand that this is inconvenient for many users, but in an effort to include users that would be otherwise excluded, we will not implement this feature.

**Comment by millette** [comment]
Seems this was implemented after all, and I'd like it reversed please - or perhaps only enable auto-focus on the frontpage. For other pages, it just makes scrolling with the keyboard harder.
