### ISSUE TITLE
Why does my package 'infamous' have so many downloads?

### ISSUE THREAD

**Issue by trusktr** [npm/www#162]
My package [`infamous`](http://npmjs.com/package/infamous) has 3000+ downloads in the past month. But I don't think that many people are actually trying to use it? It has no documentation yet, just a couple basic example in the Readme. Where are all these downloads coming from? Is it because I have a lot of keywords, that maybe some automated tools use to query packages and download them for package.json info?

**Comment by soldair** [comment]
lots of folks follow https://replicate.npmjs.com with modules like changes-stream or other couchdbs and download every tarball as it's published. 3000 seems a bit high but i haven't kept track of the ambient replicate bot rate lately

rest assured they are comming from actual requestsi cant speak as to what those folks are doing with it.
