### ISSUE TITLE
Readme not updated after new version

### ISSUE THREAD

**Issue by JbIPS** [npm/www#166]
On this [package page](https://www.npmjs.com/package/unifile) the information displayed are from the old Readme (prior to v1.0). The Readme on [GitHub](https://github.com/silexlabs/unifile/blob/master/README.md) (thus in the package) is totally different but the content didn't change.

Is there a cache that need to be clear/forced? Thanks

**Comment by aearly** [comment]
What's interesting is that there is no README in the package tarball: https://registry.npmjs.org/unifile/-/unifile-1.0.0.tgz

It's possible that the `.*` in the `.npmignore` is catching it.  (But the `npm` CLI should never ignore a `README.md`)

**Comment by JbIPS** [comment]
That's intriguing but at least it should be easy to fix, thank you for pointing that out! Next time I'll make a tarball and check the content before publishing to npm. 

I'll close this and reopen it only if it doesn't fix the page.
