### ISSUE TITLE
inconsistent "team" count in organization

### ISSUE THREAD

**Issue by stephenmathieson** [npm/www#17]
on the packages view, i see 1577 "teams":

![package-view](https://cloud.githubusercontent.com/assets/571265/17679299/b9282c4e-62ef-11e6-95ab-3a2a1b680f39.png)

on the "team" view, i only see 100:

![team-view](https://cloud.githubusercontent.com/assets/571265/17679315/c89fcf88-62ef-11e6-97a8-0c9c2e312420.png)

**Comment by jefflembeck** [comment]
hey @stephenmathieson, thanks for being patient with us. We've heard that Calvin at Segment has spoken with our support team about this issue and that it's now closed. On our end, we're in the process of making sure stuff like this doesn't happen again (a redesign of the org admin is in the pipeline). I'm going to close this issue and if you still find problems with it, let us know. Thank you!

**Comment by stephenmathieson** [comment]
sounds good! yep, calvin said he reached out. thanks!
