### ISSUE TITLE
Github does not appear on published package

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [npm/www#170]
Hello,

i have published two packages to npm. In one of them url to  Github appears on the side along with the issues count. However in another - does not. I cannot find any info in Google is there should be anything special to be done to achieve this. Can you help?

**Comment by aearly** [comment]
Do both of them have a proper `repository` field in the `package.json`?  Which packages are these exactly?

**Comment by vytautas-pranskunas-** [comment]
No, repository was not there. However, I have mentioned, that could not find on the web any info about it. Now it is ok. Thanks
