### ISSUE TITLE
redux-storage page shows Whoops Something went wrong

### ISSUE THREAD

**Issue by razzed** [npm/www#176]
Page: https://www.npmjs.com/package/redux-storage

    1495566428167:www-16-west.internal.npmjs.com:2851:j31t617m:25026

![image](https://cloud.githubusercontent.com/assets/197812/26371769/b2292a76-3fc9-11e7-9de3-6b6433f9c611.png)

Search for "redux-storage" and then click on top result from michaelcontento:

    https://www.npmjs.com/search?q=redux-storage

Note the page shows the correct content as well sometimes.

**Comment by aearly** [comment]
We had a misbehaving server yesterday, should be resolved now.
