### ISSUE TITLE
[Bug] Name entered while signup is not reflected in profile

### ISSUE THREAD

**Issue by Sibiraj-S** [npm/www#184]
While Signing up there is a name field. which I guess is same as the one in Profile. while signing up the entered username is not getting updated in the profile.

**Comment by Sibiraj-S** [comment]
anyone there?

**Comment by aearly** [comment]
What is your npm user name?

**Comment by Sibiraj-S** [comment]
@sibiraj-s. after signing up. I updated manually

**Comment by Sibiraj-S** [comment]
@aearly is this issue replicated/ confirmed?

**Comment by aearly** [comment]
Not replicated.  What was the name you used?

**Comment by Sibiraj-S** [comment]
Sibiraj

**Comment by Sibiraj-S** [comment]
Go to signup and create an account. There is a name field on that page. 
After creating account successfully. Go to profile and check the name. The field will be blank
