### ISSUE TITLE
an organization's packages should be paginated, not truncated

### ISSUE THREAD

**Issue by stephenmathieson** [npm/www#19]
trying to see what packages are available, but there are only a few of our packages in the ui :/

rather than truncating the list, it'd be super nice if it was paginated instead

**Comment by aredridel** [comment]
This is on our roadmap, but we don't have a firm schedule yet. We've a lot of plans to spruce up the organization pages and that's a part of it. Thanks for the feedback!

**Comment by stephenmathieson** [comment]
Great, thanks!!
