### ISSUE TITLE
A documentation fix request

### ISSUE THREAD

**Issue by elliot-nelson** [npm/www#190]
There's some misleading documentation on the website, here:

    https://docs.npmjs.com/misc/config

This page calls out `NPM_CONF_USERCONFIG` and `NPM_CONF_GLOBALCONFIG` as environment variable versions of `--userconfig` and `--globalconfig`.  However, these do not work -- the correct environment variables to use are `NPM_CONFIG_USERCONFIG` and `NPM_CONFIG_GLOBALCONFIG`.

Tested in npm v2.latest and npm v5.latest.

**Comment by jefflembeck** [comment]
@elliot-nelson This documentation is actually populated from the CLI itself, so I'm opening an issue over there for this. Thank you: https://github.com/npm/npm/issues/17550
