### ISSUE TITLE
Payment info page "undefined packages"

### ISSUE THREAD

**Issue by damacus** [npm/www#220]
When on the payment info page the packages section is a bit borked. 

![screen shot 2017-08-22 at 12 17 42](https://user-images.githubusercontent.com/40786/29563152-47dd27be-8734-11e7-80c8-18fb74411da3.png)

Currently we don't have any packages uploaded and looks like this on the packages page:

![screen shot 2017-08-22 at 12 21 57](https://user-images.githubusercontent.com/40786/29563223-883cc274-8734-11e7-9199-183ee0557acf.png)

**Comment by aearly** [comment]
Related: #210

**Comment by damacus** [comment]
Search fail. 

Thanks!
