### ISSUE TITLE
I keep getting "not found" pages lately.

### ISSUE THREAD

**Issue by trusktr** [npm/www#222]
It's happening often, then I can refresh and usually the page will work as normal. This is happening for legitimate packages that actually exist, for example it's happened with [`gulp-merge`](https://www.npmjs.com/package/gulp-merge) just now.

**Comment by trusktr** [comment]
Sorry, not sure what else to post. Might be worth looking in your logs.

**Comment by devpaul** [comment]
You're not alone. Posted here https://github.com/npm/npm/issues/18153. I've only been able to reproduce this on Linux systems.

**Comment by bcoe** [comment]
@trusktr we found a bug with our cache yesterday and this issue should now be resolved. sorry about that!

@devpaul I believe issues with 404s from the CLI is most likely another issue, which we will keep digging into in 18153.

**Comment by trusktr** [comment]
Hello guys, now I'm having problems with `401` errors using the cli: https://github.com/npm/www/issues/224
