### ISSUE TITLE
Noticed typo on web page

### ISSUE THREAD

**Issue by glenmriley** [npm/www#230]
Misspelling: "priotity"

**Comment by deltab** [comment]
What is the URL of the page, please?

**Comment by superplane39** [comment]
Looks like https://www.npmjs.com/package/react-keystack, @deltab.

**Comment by jefflembeck** [comment]
If a spelling error is found in a package, page, unfortunately that comes from that package's README and we have no control. It's best to open a PR with them (those kind of fixes are always welcome)
