### ISSUE TITLE
package downloads intermittently failing with 500

### ISSUE THREAD

**Issue by kayneb** [npm/www#232]
#### I'm opening this issue 
  npm is crashing.

#### What's going wrong?
Getting intermittent 500s when downloading packages and accessing npmjs packages via the website, for example https://www.npmjs.com/package/react-dom

#### How can the CLI team reproduce the problem?
`npm i react-dom` or hit `https://www.npmjs.com/package/react-dom` multiple times

Unique error number: 1504732806630:www-18-west.internal.npmjs.com:9587:j6ya4zxp:32677

**Comment by aearly** [comment]
We had a service incident today, see: https://status.npmjs.org/incidents/25brbmchw606
Shoud be back to normal now.
