### ISSUE TITLE
package json-rpc-middleware-stream erroring on webbypage

### ISSUE THREAD

**Issue by kumavis** [npm/www#233]
search results: https://www.npmjs.com/search?q=json-rpc-middleware-stream

bad link: https://www.npmjs.com/package/json-rpc-middleware-stream

err code: `1504732952731:www-16-west.internal.npmjs.com:18217:j6ya4w7q:35990`

cat: :smile_cat:

**Comment by aearly** [comment]
We had a service incident today, see: https://status.npmjs.org/incidents/25brbmchw606
Shoud be back to normal now.
