### ISSUE TITLE
1505756696629:www-16-west.internal.npmjs.com:30717:j7mc6haa:60523

### ISSUE THREAD

**Issue by fpintos** [npm/www#242]
Hello, I received this error while trying to create a new account in npmjs.com:
```
1505756696629:www-16-west.internal.npmjs.com:30717:j7mc6haa:60523
```
Thanks

**Comment by aearly** [comment]
Thanks for the bug report!  This appears to be the same issue as #238 .  Try clearing your cookies for npmjs.com, or in a different browser.

**Comment by fpintos** [comment]
I simply tried the operation again and it worked; same browser, same window.
