### ISSUE TITLE
Markdown: Link in header rendering

### ISSUE THREAD

**Issue by silverwind** [npm/www#25]
See [this link inside a `<h2>`](https://www.npmjs.com/package/droppy#features-try-the-demo).

![](https://cloud.githubusercontent.com/assets/115237/18215122/004b8288-7150-11e6-84c1-50c0fae859a2.png)

I'd say a correct rendering should not include the `:before` hash and it should likely be colored. 😉

**Comment by jefflembeck** [comment]
That’s definitely a bug! Thanks for taking the time to submit this. It’s been added to our internal tracker and will be prioritized soon.

**Comment by aredridel** [comment]
This will be fixed by the next release of [marky-markdown](https://npmjs.com/packages/marky-markdown).

**Comment by ashleygwilliams** [comment]
notably, https://github.com/npm/marky-markdown/pull/225 🐬

**Comment by ashleygwilliams** [comment]
the fix for this was merged !

**Comment by silverwind** [comment]
Working 👍
