### ISSUE TITLE
Repository link not showing

### ISSUE THREAD

**Issue by akaztp** [npm/www#253]
I have two packages on NPM:
A. [match-observable](https://www.npmjs.com/package/match-observable)
B. [router-store-ser](https://www.npmjs.com/package/router-store-ser)

Project A, shows the github repo link on NPM page with this config in package.json:
```
  "repository": {
    "type": "git",
    "url": "https://github.com/akaztp/match-observable.git"
  },
```

Project B, **does not** show the github repo link on NPM page with this config in package.json:
```
  "repository": {
    "type": "git",
    "url": "https://github.com/akaztp/router-store-ser.git"
  },
```

I've compared everything again and again and I don't find the culprit!

**Comment by JWebCoder** [comment]
Same issue here too.

**Comment by ghybs** [comment]
Hi @akaztp,

Your project B [last published version (i.e. `1.0.1`)](https://www.npmjs.com/package/router-store-ser/v/1.0.1)'s `package.json` **does not** include yet the expected [`repositiory`](https://docs.npmjs.com/files/package.json#repository) field:
- https://github.com/akaztp/router-store-ser/blob/1.0.1/package.json
- https://unpkg.com/router-store-ser@1.0.1/package.json

Obviously `npm` knows only about the published versions, but nothing about your GitHub committed version beyond that point.
Therefore the simple solution seems to be to publish a new version of your package, even just for the sake of adding this field and link (in semver, a simple patch version bump would be appropriate even just for this).

Hope this helps.

**Comment by akaztp** [comment]
Yes, I've just realized that package.json in the master branch has the repository field but not in the v1.0.1 branch!!
Thanks a lot!!
