### ISSUE TITLE
Show additional information on organization pages

### ISSUE THREAD

**Issue by adius** [npm/www#26]
At the moment there is just a list of the package-names:

![image](https://cloud.githubusercontent.com/assets/969983/18268816/fde77458-7414-11e6-836d-d2de018f2020.png)

It would be cool if there were more infos like:

- Latest version
- Publish date
- Maintainers
- …

**Comment by aredridel** [comment]
Thanks for taking the time for the feature request! We, luckily enough, have that page coming down the pipeline at some point hopefully in the near future and love your ideas and will be sure that our designer sees them.

**Comment by isaacs** [comment]
cc: @gabra
