### ISSUE TITLE
JSX Comment Highlighting

### ISSUE THREAD

**Issue by brigand** [npm/www#267]
If this issue belongs on some syntax highlighting library you use, please point me to the repo.

## Link to the page

[react-ck5](https://www.npmjs.com/package/react-ck5#propseditorstate-and-propsonstatechange).

![react-ck5 readme on npmjs.com](https://user-images.githubusercontent.com/936069/32349287-c40d8324-bfd3-11e7-8f20-039e4dec5891.png)

## Logged in or logged out?

Logged in

## Expected behavior

Comments in jsx attribute positions should look like comments. The [spec](https://facebook.github.io/jsx/) doesn't mention this explicitly, but babel, acorn, typescript, and flow all support the syntax.

## Actual behavior

Comments are highlighted weirdly.

## Steps to reproduce the problem

1. Put this in readme.md

![jsx markdown example](https://user-images.githubusercontent.com/936069/32349454-5a6c3b44-bfd4-11e7-8d66-8132829b5e9e.png)

2. Publish to npm
3. view website

## Browser with version

Chrome Latest

## Any error message?

Nope

Thanks!

**Comment by ashleygwilliams** [comment]
hey @brigand ! thanks for filing this :) as you suspected, this is actually an error with highlight.js which is leverage by our markdown parser marky-markdown. you probably want to file here: https://github.com/isagalaev/highlight.js

:) if you need help getting that through, you can also file on https://github.com/npm/marky-markdown as we helped get the JSX parsing through in the first place. good luck! closing.
