### ISSUE TITLE
Wrong npm version of gulp-html-autoprefixer

### ISSUE THREAD

**Issue by karolchmist** [npm/www#27]
Hello, 

We use npm with shrinkwrap in our project, with gulp-html-autoprefixer as a dependency in package.json. 

We fixed it at 0.**1**.0 some time ago, the same as the latest dependency in their github :
https://github.com/Rebelmail/gulp-html-autoprefixer/blob/a0d226053c1e1507c1669ed991a17b990a795b70/package.json

Unfortunately and apparently for some time now, the latest version reported by npm is 0.0.**1**
https://www.npmjs.com/package/gulp-html-autoprefixer

When we run `npm install`, it won't find the latest version (0.1.0), forcing us to use the previous one (0.0.1).

Would it be possible to update it to the latest versin? Is there a bug causing it take the previous one? 

Thanks!

**Comment by aredridel** [comment]
I took a brief look at this and it does not appear that version 0.1.0 is published to the registry. 

This isn't a website bug -- the website just reflects what's in the registry -- so I'm going to close this issue.

If you need support, contacting support@npmjs.com is the best way. 

At a glance, though, publishing version 0.1.0 as it is in github should get you on your way again.
