### ISSUE TITLE
Feature request - Sort profile packages alphabetically

### ISSUE THREAD

**Issue by borela** [npm/www#276]
## Link to the page
Go to any user profile.

## Logged in or logged out?
Both.

## Expected behavior
Show the package list owned by that user sorted alphabetically.

## Actual behavior
Messy.

## Browser with version
Any browser.

## Any error message?
No.

**Comment by LukeSheard** [comment]
Why is this not done already? I just realise this and it's really annoying...

**Comment by borela** [comment]
This was implemented in the new site.
