### ISSUE TITLE
Error on Profile edit > Save

### ISSUE THREAD

**Issue by jankal** [npm/www#288]
## Link to the page
https://www.npmjs.com/profile-edit

## Logged in or logged out?
Logged in but logged out afterwards.

## Expected behavior
Saves my profile.

## Actual behavior
Loggs me out and sends error message

## Steps to reproduce the problem
1. Login to npmjs.com
2. Click on profile > Personal Info
3. Insert values for name, github, twitter, and website

## Browser with version
Firefox 57.0.3

## Any error message?
```
1515057602712:www-19-west.internal.npmjs.com:30161:jbxpul40:80371
```

**Comment by jankal** [comment]
I just tried this again:

![Inserting info](https://user-images.githubusercontent.com/6324332/34557118-7c6b91ea-f139-11e7-9053-2a17e2ba54c4.png)

Yields:
![Error](https://user-images.githubusercontent.com/6324332/34557159-9662b8bc-f139-11e7-8260-380862f1f30a.png)

**Comment by jankal** [comment]
Related: #247

**Comment by aearly** [comment]
This is likely related to a change we made yesterday.  You now have to specify `http://` or `https://` in your homepage URL.

**Comment by jankal** [comment]
@aearly It's not shown in the example. You should add it there.
So probably one can close this issue then.

**Comment by aearly** [comment]
Yep, good idea, I added `https://` to the example there.  The [new website](https://preview.npmjs.com) (!!!) will have much more user-friendly validation for those fields.
