### ISSUE TITLE
ampersands in package descriptions get double-encoded

### ISSUE THREAD

**Issue by nfriedly** [npm/www#29]
npmjs.com is double-encoding ampersands (&) from the description line in package.json.

So, [this](https://github.com/watson-developer-cloud/ui-components/blob/master/package.json#L4):
![screen shot 2016-09-16 at 12 05 07 pm](https://cloud.githubusercontent.com/assets/114976/18592633/d8a50b58-7c05-11e6-8040-da08cad8ab81.png)

Turns into [this](https://www.npmjs.com/package/watson-ui-components#237):
![screen shot 2016-09-16 at 12 11 07 pm](https://cloud.githubusercontent.com/assets/114976/18592825/b0cec9d8-7c06-11e6-80ee-7b640fb96e52.png)

Which renders as [this](https://www.npmjs.com/package/watson-ui-components):
![screen shot 2016-09-16 at 12 11 54 pm](https://cloud.githubusercontent.com/assets/114976/18592849/ca9bd914-7c06-11e6-8d67-00e8358ee54d.png)

It's not the end of the world, but it's not correct either :/

**Comment by tkazec** [comment]
Same with double quotes, which become `&quot;`.

**Comment by ashleygwilliams** [comment]
this should land in the website soon! thank you all for filing!
