### ISSUE TITLE
Can't submit forms (login & forgot page)

### ISSUE THREAD

**Issue by tarto-dev** [npm/www#292]
## Link to the page
https://www.npmjs.com/forgot

## Logged in or logged out?
Logged out

## Expected behavior
Login to the website

## Actual behavior
It fully works on mobile, but once I try on desktop, I can't post any form : login fail, forgot password too, and every tries seems fail too. Even if I try with stupid credentials (e.g: aa/aa), it seems fail too : does it reach the webserver ?

## Steps to reproduce the problem
1. Go to forgot password page, write a mail address, then submit the form. 

## Browser with version
Tested under Chrome 63.0.3239

## Any error message?
1516876605360:www-18-west.internal.npmjs.com:19985:jchw67lx:27531

**Comment by jefflembeck** [comment]
@benftwc can you try this on preview.npmjs.com and tell me if you're running into the same error?

**Comment by mehyaa** [comment]
preview.npmjs.com worked for me for sign up.

**Comment by tarto-dev** [comment]
Sorry, I did not receive notifications ...

Everything work fine now, I cound sign on preview.npmjs.org
