### ISSUE TITLE
Privacy / SPAM Issue (Email Addresses are limitless visible and published on profiles on the website)

### ISSUE THREAD

**Issue by monbro** [npm/www#296]
I am aware that this is still an issue to some people, so I would like to spread the word to open a new issue on this: https://github.com/npm/www/issues/16 and to raise awareness in the community.

No one of the NPM team takes responsibility / action on this. Are you a proper company already? ;)

My own solution now was to use a fake email address for my npm account. Is that the only solution I as a user have? Example: https://preview.npmjs.com/~monbro (not logged in users see the email address) while https://www.npmjs.com/~monbro my email is visible to members only (don't tell me bots can't access it then because of this).

My very big personal issue with this is, that because of this the SPAM level in my INBOX increased obviously as bots fetching email addresses in the web. And my email address has been on your page for ~4 years now. Thank you for this as this slows down my process of responding and being productive (because more spam comes in, marked as spam and not marked), thank you again.

Please everyone, put your thoughts on this here.

**Comment by monbro** [comment]
According to http://blog.npmjs.org/post/94662089625/the-future-of-the-npm-website-lets-map-this the website https://preview.npmjs.com/ is available public since 2014, which confirms that emails have been public accessible since that time of every user who every published.

**Comment by monbro** [comment]
**Oh wow guys, you just changed that without any notice to anyone.**  (No Email anymore displayed on e.g. https://preview.npmjs.com/~diurnalist)

Thanks for the conversation, I will talk to the wall in my room now, it gives the same love and care in response to me like you guys do.

-- 

Still an issue is now, that on the main website https://www.npmjs.com/~diurnalist (if logged in) I see everyones email. Issue here:

1.) Bot or Bot owner creates an account
2.) Bot scrapes all the emails
3.) Bot sends spam to all 4 million or more npm users (http://blog.npmjs.org/post/143451680695/how-many-npm-users-are-there)

**Comment by monbro** [comment]
In case you want now to deny everything, I was nasty and found a proof on the most hated website of the web https://web.archive.org/web/20170927015046/https://www.npmjs.com/~phated or https://web.archive.org/web/20170927013239/https://www.npmjs.com/~vladikoff (I also don't like archive.org).

**Comment by shirakaba** [comment]
Interesting; I certainly saw your email visible on https://preview.npmjs.com/~monbro (it showed a GitHub no-reply email, incidentally) when this issue was first opened, so perhaps they're finally doing some work on this. Would be nice if they had mentioned it. I'll be keeping an ear out for any news.

**Comment by shama** [comment]
@monbro Maybe sending an email to every person affected by this wasn't the best way to show you don't like spam? I personally would have just sent an email to npm's security channel and then used patience. But I guess if you're really upset about it, then spam npm and not me, thanks! :)

**Comment by monbro** [comment]
@shama I am certainly not going to discuss with you what spam actually is. If this issue is none of your concern, I am sorry that I tried to raise some of your attention.

But actually it should, considering that bots scraping websites every second for email addresses etc. and sending rubbish into your and my inbox. If this was a website with 10 users I would not care, but with more then 4 million I don't feel like staying silent. Hint: maybe this is not only about you and me.

**You can also think of it like this:** What about all the users who are not aware (and probably would care) about their email address being that easy accessible as it isn't usual on most websites? When I enter my email for creating an account I am NOT assuming it is visible public and / or visible to members. Even as it is named "public email" (on reg), when I started publishing packages this was not clear to me at all.

Another background is, that I am hoping to put some attention on #16 which is more about the email visibility to other members and quite old as you can see.

**Comment by shama** [comment]
@monbro Do you not see the irony in what you have done? You broke into my house to tell me my door is unlocked.

**Comment by jefflembeck** [comment]
Hey all, thanks for taking the time to comment about this (and open up other issues regarding it). We know this is a serious subject and apologize for the time it has taken to get to a solution. Truth be told, as @aredridel mentioned a while back, we've kept emails available on public profiles as a mechanism for people to reach out to one another to handle package help and disputes. When email is not on the page, our support requests increase by a lot, and npm is not a large company with a huge support team (5 people for 11 million users).

In making this decision and waiting for the time when our tiny web team (2.5 dedicated people - seriously) could get to creating a perfect solution, we've allowed this to go on for too long and instead put the problem on your (our users) shoulders, and this was the wrong thing to do.

As you may have seen or heard, we're rewriting the website right now from the ground up. You can access it at https://preview.npmjs.com. It updates basically as we merge commits to master and _is_ a beta, so I hope you can understand if it's missing some functionality or has a few bugs (feel free to open up issues here if you see them though, it's really quite helpful for our internal tracking)! You'll notice there that we've removed the email address from the profile page. This should be a permanent change.

The new site will replace the old site in entirety quite soon, and when it does so, 🎉 . It will help us be able to address outstanding features like this a lot faster and will give you a lot better experience all together. We really hope you like it.

Thanks again

**Comment by monbro** [comment]
All I could have hoped for 🎉  🎉  🎉  thanks for responding and taking responsibility.

**Comment by TheJaredWilcurt** [comment]
It doesn't change the fact that the email address is still attached in the meta data and that you require validating email addresses.

This is what is on the preview profile page:

```
This email will be added to the metadata of packages you publish
```

Do what GitHub does, have a **100% PRIVATE** login email that is verified, and then allow a *different* email address for publishing and public display. And do NOT default to using their private email for the public one, force users to opt-in to that.

This shouldn't be that hard.

Also, if you're going to be the only website on earth to **force** lowercase usernames, then why they hell don't you do some inline form validation on the login screen, or better yet, just `toLowerCase()` for the user. OR, OR, get this.... don't force lowercase usernames at all :open_mouth: 

Here I made you a mockup:

![npm signup](https://user-images.githubusercontent.com/4629794/35953113-16e95d24-0c51-11e8-8d3e-eebad60d5547.png)
