### ISSUE TITLE
1517503352730:www-18-west.internal.npmjs.com:11728:jcwhm7a9:39167

### ISSUE THREAD

**Issue by Pliman** [npm/www#298]
## Link to the page
https://www.npmjs.com/~pliman
## Logged in or logged out?
Y
## Expected behavior
Do you need us to send it again? - expect resend email
## Actual behavior
Whoops
Something went wrong and this error code
## Steps to reproduce the problem
1. click 'Do you need us to send it again?' on my profile page

## Browser with version
chrome 63.0.3239.132
## Any error message?

**Comment by GoddessMaat** [comment]
yes please resend

**Comment by Pliman** [comment]
"Your email has been verified. Thank you!"

Great!!! Thank you @GoddessMaat
