### ISSUE TITLE
Single-character packages can't be found by searching on npmjs.com

### ISSUE THREAD

**Issue by laosb** [npm/www#303]
## Link to the page

https://www.npmjs.com/search?q=a
https://www.npmjs.com/search?q=b
https://www.npmjs.com/search?q=c
...

## Logged in or logged out?

Doesn't matter.

## Expected behavior

Found that corresponding single-character-named package.

## Actual behavior

0 packages found for "`[a-z]`"

## Steps to reproduce the problem
1. Type one letter in the search box and hit `return`.

## Browser with version

Chrome 64.0.3282.140 macOS.
I don't think it's browser-specific.

## Any error message?

Nope, no related error messages found.

Actually, this works on npms.io, which is said to provide searching for npmjs.com.

And you can still get access to them on npmjs.com, by directly typing URL. like:

https://www.npmjs.com/package/a
https://www.npmjs.com/package/b
https://www.npmjs.com/package/c
...

**ProTip:** We have all `a-z` packages on npm, while package [`r`](https://www.npmjs.com/package/r) doesn't do anything and seemed only published for reserving the name. Some of them are really famous, like [`n`](https://www.npmjs.com/package/n).

**Comment by aearly** [comment]
We disabled single-character queries because it causes excessive load on our search backend.  However, in the upcoming version of npm's website, we are having single-char queries take you directly to that package:

https://preview.npmjs.com/search?q=q

**Comment by aearly** [comment]
Fixed!
