### ISSUE TITLE
/pricing link in the new site redirects to the package "pricing"

### ISSUE THREAD

**Issue by laggingreflex** [npm/www#304]
## Link to the page

https://preview.npmjs.com/pricing

redirects to the package "pricing"

https://preview.npmjs.com/package/pricing

instead of like https://www.npmjs.com/pricing

**Comment by jefflembeck** [comment]
@laggingreflex oh wow thank you! will make sure to add to our internal tracker

**Comment by sompylasar** [comment]
The same for /features

**Comment by jefflembeck** [comment]
Fixed. Thanks
