### ISSUE TITLE
Broken link to scopes from publish page

### ISSUE THREAD

**Issue by seattlevine** [npm/www#308]
## Link to the page
https://docs.npmjs.com/getting-started/publishing-npm-packages

## Logged in or logged out?
Logged in

## Expected behavior
Link to scopes in this line:
Note: The first 3 caveats don't apply if you are using scopes.
points to https://docs.npmjs.com/misc/scope

## Actual behavior
Link to scopes in this line:
Note: The first 3 caveats don't apply if you are using scopes.
points to https://docs.npmjs.com/cli/version

## Steps to reproduce the problem
1. Visit https://docs.npmjs.com/getting-started/publishing-npm-packages
2. Click on 'scopes' in the line 'Note: The first 3 caveats don't apply if you are using scopes.'

## Browser with version
Chrome 63

## Any error message?
No

**Comment by seattlevine** [comment]
Or maybe it should point here:
https://docs.npmjs.com/getting-started/scoped-packages

**Comment by jefflembeck** [comment]
Thanks! Opened an issue above in our docs repo
