### ISSUE TITLE
website rendering escapes single backslash in inline code block (`\`)

### ISSUE THREAD

**Issue by poiuiopoiu** [npm/www#31]
NPM appears to use a parser that follows the common mark spec and it differs from github in a few ways.  My issue is writing a single backslash in an inline code block.

The Github way is 

```
`\`
```

But that trips up the NPM parser, since common mark treats that as an escaped backtick.  The right way to do it for NPM is

```
`\\`
```

But that messes up github, which interprets it as 2 backslashes.

I'd guess that most modules use the github markdown style, so I guess I would consider this a npm website bug

**Comment by ashleygwilliams** [comment]
hi! this issue is actually related to the markdown parser that the npm website uses. the parser is called [marky markdown](https://github.com/npm/marky-markdown). 

i've moved your issue there. thanks for filing this! we'll get right on it :)

**Comment by ashleygwilliams** [comment]
actually, after testing with marky- this looks like it *is* a website issue. likely perpetrated by the templating engine. may be related to https://github.com/npm/www/issues/29

reopening this and closing the marky issue.

**Comment by ashleygwilliams** [comment]
hey @jefflembeck - wanna pair on this next week? or later this week? lemme know :)

**Comment by aredridel** [comment]
I can't replicate this.

github:
<img width="919" alt="screen shot 2016-10-20 at 11 05 56" src="https://cloud.githubusercontent.com/assets/2876/19565552/353478b2-96b5-11e6-877f-796d3d30dd97.png">

npm:
<img width="746" alt="screen shot 2016-10-20 at 11 05 49" src="https://cloud.githubusercontent.com/assets/2876/19565551/35227590-96b5-11e6-83bf-1dc361fa5163.png">

**Comment by aredridel** [comment]
Is there a package that has the bad readme for you @poiuiopoiu ?

**Comment by poiuiopoiu** [comment]
@aredridel thank you for replying!  I set up a dummy package `badness-10000` to demonstrate:

```
# badness 10000

| a | b | c | d | e | f |
|---|:-:|---|:-:|---|:-:|
| `a` | b | `c` | d | `` ` `` | |
| `e` | f | `g` | h | `|` | |
| `\` |   | `]` |   | `[` | |
```

github: https://gist.github.com/poiuiopoiu/fa85d4166a273ec7692d227028336ac5

<img width="264" alt="screen shot 2016-10-30 at 12 12 21" src="https://cloud.githubusercontent.com/assets/22307420/19839151/2b08621c-9e9a-11e6-90d5-7d107d5e9e0f.png">

NPM: https://www.npmjs.com/package/badness-10000

<img width="607" alt="screen shot 2016-10-30 at 12 11 52" src="https://cloud.githubusercontent.com/assets/22307420/19839144/2706f44e-9e9a-11e6-8962-429144912e7e.png">

Please feel free to completely remove all versions of the package -- I have no plans to use the name.

**Comment by aredridel** [comment]
Oho! That helps -- inside table markup is a whole other beast!

**Comment by aredridel** [comment]
Oh, inside tables! That would explain it, there's a lot of special cases there I bet.

**Comment by ashleygwilliams** [comment]
can confirm this is a marky bug. reopened: https://github.com/npm/marky-markdown/issues/252

**Comment by revin** [comment]
@poiuiopoiu the fact that this is definitely a bug notwithstanding, I think you can surround the slash with spaces and get the result you want across both platforms: `` ` \ ` `` (i.e., backtick + space + slash + space + backtick) should render as `\` everywhere, even inside a table.

**Comment by ashleygwilliams** [comment]
this was solved by merging https://github.com/npm/marky-markdown/pull/283.

see: https://www.npmjs.com/package/badness-10000
<img width="826" alt="screen shot 2017-02-03 at 5 48 05 pm" src="https://cloud.githubusercontent.com/assets/1163554/22611506/f0f2841e-ea38-11e6-9d1f-7bd54f983528.png">
