### ISSUE TITLE
Signup at npmjs.com is not possible - 1518608378567:www-17-west.internal.npmjs.com:7664:jdluer7g:84844

### ISSUE THREAD

**Issue by renepardon** [npm/www#313]
## Link to the page

https://www.npmjs.com/signup

## Logged in or logged out?

logged out

## Expected behavior

logged in after signup ; receive email confirmation after signup

## Actual behavior

    Whoops
    Something went wrong
    
    If you feel this error is the result of a bug, please email us, send us a tweet, or reach out to us on GitHub and reference the following unique error number:
    
    1518608378567:www-17-west.internal.npmjs.com:7664:jdluer7g:84844
    
    Be sure to let us know what you were doing and how you got here so we can help you as quickly as possible!

## Steps to reproduce the problem
1. Create a new account.

## Browser with version

Firefox 58.0.2 (64-bit) (macOS High Sierra)

## Any error message?
see actual behaviour

**Comment by renepardon** [comment]
Refreshed the page and resend the signup data - now I'm in. But I think this issues has to be fixed.

**Comment by tegud** [comment]
I'm also experiencing this problem, trying to create and org or a personal account, tried refreshing and retrying, but always the same error, example Error:

1518683987046:www-17-west.internal.npmjs.com:7664:jdluer7g:17829
