### ISSUE TITLE
Table thead content coerced to lower case

### ISSUE THREAD

**Issue by jrpool** [npm/www#316]
## Link to the page

https://www.npmjs.com/static/css/index.css

## Logged in or logged out?

Either

## Expected behavior

table thead tr {
  height: 30px;
}

## Actual behavior

table thead tr {
  height: 30px;
  text-transform: lowercase;
}

## Steps to reproduce the problem
1. To view an example of the problem, visit https://www.npmjs.com/package/jsonresume-theme-a11y and look at the table headings. Then go to the Github repo of that package and look at the same table. The table should look as it does on Github, not as it looks on NPM.

## Browser with version

Any

## Any error message?

No

**Comment by aearly** [comment]
We've recently revamped the package page on the upcoming version of the site. Does it look good on https://preview.npmjs.com ?

**Comment by jrpool** [comment]
Thanks! Yes, the table headings are no longer decapitalized in the preview. That’s great.

However, in the preview there is additional vertical space above and below headings. It seems to be too much space. The current spacing is better.
