### ISSUE TITLE
"website issues" link on website has typo in link to this issue tracker

### ISSUE THREAD

**Issue by serhalp** [npm/www#33]
Hi! The "website issues" link, which I've deduced should link to this very issue tracker, appears to have the extra characters `we` in it for some reason – like so: https://github.com/npm/newww/issues.

<img width="1208" alt="screen shot 2016-09-20 at 10 01 06 pm" src="https://cloud.githubusercontent.com/assets/1377702/18698289/d69a5126-7f7d-11e6-9e8d-c7541a13ea6d.png">

Oops! Ironically, it took me a while to find where to post this issue ;)

**Comment by ashleygwilliams** [comment]
submitted a PR for this: https://github.com/npm/npm-website/pull/635

**Comment by serhalp** [comment]
Even more ironically, that link is broken too. Or it's just a private repo!

**Comment by ashleygwilliams** [comment]
😆  hey @serhalp - it's a private repo. but that woulda been pretty hilarious.
