### ISSUE TITLE
organism-react-carousel's package version not update to latest.

### ISSUE THREAD

**Issue by HillLiu** [npm/www#333]
## Link to the page
https://www.npmjs.com/package/organism-react-carousel

## Logged in or logged out?
logged in

## Expected behavior
package version should update to 0.0.34

## Steps to reproduce the problem
1. go to https://www.npmjs.com/package/organism-react-carousel
check package version not update

## Browser with version
chrome.

## Any error message?
none.

**Comment by driedelreply** [comment]
Currently it seems the registry has some mayor issues as pushed new versions are not promoted to the query part. Its currently not possible to update npm packages to a latest version that is pushed in the last hour

**Comment by HillLiu** [comment]
duplicate with https://github.com/npm/npm/issues/20077
