### ISSUE TITLE
Site error: delete organization request

### ISSUE THREAD

**Issue by EthanLin-TWer** [npm/www#336]
## Link to the page

https://www.npmjs.com/support

## Logged in or logged out?

Logged in.

## Expected behavior

I was writing help wanted email to npm support, and I should be able to send out the email successfully in order to reach out for help.

## Actual behavior

![image](https://user-images.githubusercontent.com/11895199/37695400-f798fbd0-2d09-11e8-8e8f-442cb3e3dc4f.png)

## Steps to reproduce the problem

I am not reporting a bug though... 

Any admin who sees this issue, would you be able to help me delete an organization 'China-Merchants-Bank' and every published packages under it?  Many thanks and reach out for more information if you needed.

**Comment by jefflembeck** [comment]
@linesh-simplicity please email support@npmjs.com and they should be able to help you
