### ISSUE TITLE
feature request: support the old packagesPerPage query

### ISSUE THREAD

**Issue by stefee** [npm/www#339]
## Link to the page

https://www.npmjs.com/org/choojs?packagesPerPage=1000

https://www.npmjs.com/org/condenast?packagesPerPage=1000 (I am a member of this org so I see lots more packages here)

## Logged in or logged out?

Either

## Expected behavior

Shows the specified packages per page

## Actual behaviour

Shows only default number of packages on page

## Steps to reproduce the problem
1. Visit an org OR user page
2. Append `?packagesPerPage=1000` to the URL
3. Scroll down and note the number of packages being displayed has not changed

## Browser with version

Google Chrome Version 65.0.3325.162 (Official Build) (64-bit)
macOS High Sierra v10.13.3 (17D102)

## Any error message?

No

**Comment by jefflembeck** [comment]
@srilq sorry for changing this on you!  `?perPage=` oughta do the trick!

**Comment by stefee** [comment]
@jefflembeck ah, doesn't seem to be working!

https://www.npmjs.com/org/choojs?perPage=1000

<img width="1175" alt="screen shot 2018-03-21 at 9 27 00 pm" src="https://user-images.githubusercontent.com/18026180/37738363-aa728b10-2d4e-11e8-8bdd-8bc28022f28d.png">

**Comment by stefee** [comment]
Created new issue #351.
