### ISSUE TITLE
Package pages are out-of-date

### ISSUE THREAD

**Issue by andy-ms** [npm/www#34]
Some pages on the npmjs.com don't reflect the latest version of the package.

For example: [convict](https://www.npmjs.com/package/@types/convict).
According to the page: "types published 4 weeks ago" and "0.6.32 is the latest of 13 releases".
But according to `npm info @types/convict`, version `0.6.33` was published 3 days ago (Sep 19).

This may be because of our publish script: we are directly using the [publish](https://github.com/npm/npm-registry-client#clientpublishuri-params-cb) method from npm-registry-client.
Currently we use a very simple [technique](https://github.com/Microsoft/types-publisher/blob/master/src/lib/npm-client.ts#L35) to get the metadata: we read in the contents of README.md and attach it to the package.json.

Similar to #11, I suspect that we are still not providing all of the metadata needed. Is there something else we need to be doing there?

Here is the list of packages with outdated pages (produced by a [script](https://github.com/Microsoft/types-publisher/pull/145/files)):
* `@types/convict`
* `@types/escodegen`
* `@types/eventemitter3`
* `@types/express`
* `@types/jdataview`
* `@types/js-cookie`
* `@types/js-yaml`
* `@types/parse5`
* `@types/passport`
* `@types/pathwatcher`
* `@types/pg`
* `@types/tape`
* `@types/temp`
* `@types/thrift`

**Comment by jdalton** [comment]
I've seen this with [lodash-migrate](https://www.npmjs.com/package/lodash-migrate) too. It should be on version `0.3.6` but is showing `0.3.4`.

**Comment by swashcap** [comment]
Noticed this after publishing one of our modules. Both the README and version number are out of date.

  * npm page: https://www.npmjs.com/package/coinstac-simulator (shows `v2.0.8`, old README)
  * Source README: https://github.com/MRN-Code/coinstac/blob/6b73bcc8130ed7db5736a8598f1f4d02179f63af/packages/coinstac-simulator/README.md (at current version, `v2.0.9`)

**Comment by cdaringe** [comment]
i noticed this last night.  further, today, it looks like it _tried_ to updated, but what rendered is in fact partial old content and partial new content.

for instance @ https://www.npmjs.com/package/counsel,

the bulk of the readme is from `0.0.0`,

but poorly rendered badge showed up in `0.0.2/3`.

looks like there's some README trash happenin!

**Comment by ashleygwilliams** [comment]
hi all! thanks so much for following this. this is actually more of an issue with the backend of the website, and should therefore should probably live here: https://github.com/npm/registry

there is already an issue open here: https://github.com/npm/registry/issues/42

there are several suggestions by both registry engineers and other users to help work around this issue while we work on a fix. sorry- i know this must be really frustrating.

i'll be closing this. please feel free to continue comment on the registry issue!
