### ISSUE TITLE
Box shadow on code blocks

### ISSUE THREAD

**Issue by swashcap** [npm/www#340]
## Link to the page

Example: https://www.npmjs.com/package/lodash

## Logged in or logged out?

Logged out!

## Expected behavior

Browser renders code blocks differently.

Safari 11.0.3:

![make-it-pop](https://user-images.githubusercontent.com/1858316/37738443-4501eb2a-2d14-11e8-8b6d-2cd1a9d29271.jpg)

Firefox 58:

![so-very-ff](https://user-images.githubusercontent.com/1858316/37738481-6081d2c0-2d14-11e8-932c-bf3b02827f48.jpg)

## Actual behavior

The code blocks have a box shadow in Safari. This is due to the `.readme__readme___tmT33 pre` class rule:

```css
.readme__readme___tmT33 pre {
  /* ... */
  box-shadow: 0 1px 1px rgba(0,0,0,0.0.05);
}
```

Safari seems to parse the malformed `0.0.05`, but other CSS engines recognize as invalid and ignore the `box-shadow` rule entirely.

## Steps to reproduce the problem

(Visit any of the package pages)

## Browser with version

Safari 11.0.3 on macOS 10.13.3.

## Any error message?

n/a

P.S. :heart: Love the new redesign! Great work!

**Comment by aearly** [comment]
Fixed, will be deployed shortly!
