### ISSUE TITLE
Remove username from settings page URLs?

### ISSUE THREAD

**Issue by billyjanitsch** [npm/www#342]
## Link to the page

https://preview.npmjs.com/settings/...

## Logged in or logged out?

Logged in.

## Expected behavior

I would expect settings pages to have URLs that don't vary between users. For example, if I want to send a link to everyone in my company to turn on 2FA, I would expect to be able to link to https://www.npmjs.com/settings/tfa

## Actual behavior

Instead, all of the settings pages are prefixed with https://www.npmjs.com/settings/$username. So there's no way to link everyone to the 2FA page because everyone's URL is different.

## Steps to reproduce the problem

See above.

## Browser with version

Chrome 65.0.3325.162

## Any error message?

No.

**Comment by jefflembeck** [comment]
@billyjanitsch Great idea. I've got a fix in that we'll be deploying today that will have:

`/settings/~/tfa` etc. be valid options.
