### ISSUE TITLE
Dependant count should not be negative

### ISSUE THREAD

**Issue by Krinkle** [npm/www#343]
## Link to the page

<https://www.npmjs.com/package/grunt-npmcopy?activeTab=dependents>

<img width="845" alt="screen shot 2018-03-21 at 19 12 12" src="https://user-images.githubusercontent.com/156867/37747296-c7ab64ee-2d3b-11e8-8bf8-48d959a92d57.png">

## Logged in or logged out?

Logged out.

## Actual behavior

The number `-5` (negative 5) is displayed.

## Expected behavior

This tab should list 0, or no number, or no tab at all.

## Other

Also, once you click on the negative number on the dependants page, it has an infinite "Next page" sequence. This is bad for usability, performance, crawlers, indexing etc. Should probably be disabled as well.

1. https://www.npmjs.com/package/grunt-npmcopy "Dependants"
2. https://www.npmjs.com/package/grunt-npmcopy?activeTab=dependents "-5"
3. https://www.npmjs.com/browse/depended/grunt-npmcopy "Next page"
4. https://www.npmjs.com/browse/depended/grunt-npmcopy?offset=216 "Next page"
5. https://www.npmjs.com/browse/depended/grunt-npmcopy?offset=252 "Next page"
6. etc.

**Comment by jefflembeck** [comment]
Filed internally. Thank you. Great catch!

**Comment by jefflembeck** [comment]
We've got a fix in, it'll be deployed today or tomorrow. Thanks!

**Comment by Krinkle** [comment]
@jefflembeck Thanks, I've confirmed the negative-count is now gone. But, it seems the pager issue still exists!

**Comment by jefflembeck** [comment]
@Krinkle yeah, that's the part that won't be deployed until later today or tomorrow 😄
