### ISSUE TITLE
Cursor position in search field resets after each value change

### ISSUE THREAD

**Issue by IllusionMH** [npm/www#345]
## Link to the page
https://www.npmjs.com/search?q=npm

## Logged in or logged out?
Logged out (but doesn't matter)

## Expected behavior
I'm able to type more than one character without caret position reset

## Actual behavior
Each time when field value changes - cursor position is reset to the end of input, which make it hard to type more than one letter.

## Steps to reproduce the problem
1. Open any page with search field (https://www.npmjs.com/search?q=npm or https://www.npmjs.com/)
2. Type something in field (e.g. `npm` or have it prefilled from search)
3. Place cursor at the beginning of the field
4. Type `1` twice
5. Observe result `1npm1` instead of `11npm`

## Browser with version
Any browser. 
Microsoft Edge 41.16299.248.0 (Microsoft EdgeHTML 16.16299)
Chrome 65.0.3325.181
Firefox 59.0.1

## Any error message?

**Comment by LMLB** [comment]
FYI: You can use https://npms.io/ as a workaround (it's what npmjs.com uses).

**Comment by katiefenn** [comment]
@IllusionMH Fixed! This change will be deployed shortly. Thank you very much for reporting this problem!

**Comment by IllusionMH** [comment]
Works great. Thank you!
