### ISSUE TITLE
Small font size inside <pre> blocks

### ISSUE THREAD

**Issue by robcresswell** [npm/www#347]
## Link to the page

https://www.npmjs.com/package/vue-material-design-icons

## Logged in or logged out?

Both

## Expected behavior

Well-sized text inside code blocks

## Actual behavior

Font size inside code blocks has 0.8rem modifier, meaning it defaults to around 12.8px in Chrome and Firefox. This is fairly subjective, but I'd argue this is too small for comfortable reading for some people. I'm not sure there is any specific reason for it to be smaller, and it could probably be the same size as regular text without losing any functionality.

## Steps to reproduce the problem
1. Load the linked page in any browser

## Browser with version

Specifically tested with Firefox 59.0.1 and Chrome 65.0.3325.181

## Any error message?
N/A

**Comment by jefflembeck** [comment]
We've increased the size, hopefully this works nicely with the font choice. Thanks!
