### ISSUE TITLE
Weekly download statistics start before the project existed

### ISSUE THREAD

**Issue by robcresswell** [npm/www#349]
## Link to the page
https://www.npmjs.com/package/vue-material-design-icons

## Logged in or logged out?
Both

## Expected behavior
Only show data from the lifetime of the project

## Actual behavior
Able to see weekly values before the project even existed, which will always be 0. When using OSS work as self-promotion in CVs etc, its not ideal to show a false 0 download figure.

## Steps to reproduce the problem
1. Load any package, view statistics graph on right hand side.

## Browser with version

Specifically tested with Firefox 59.0.1 and Chrome 65.0.3325.181

## Any error message?
N/A

**Comment by chrisdickinson** [comment]
Thanks for the bug report! This is a ~surprise feature~ bug in our download-counts API. When a package has been published then unpublished, and is later published, the download counts from the original package will still appear on the graph.

**Comment by chrisdickinson** [comment]
I've refiled this on the registry repo, since we'll need to tackle this work over there. Thank you for the report!

**Comment by robcresswell** [comment]
That's really interesting. I don't recall publishing then unpublishing... Could I have taken a namespace someone had before? Maybe my memory is just poor. Thanks for posting the other bug report for me.
