### ISSUE TITLE
A page link on header is resolving to a user package

### ISSUE THREAD

**Issue by mohitsinghs** [npm/www#350]
The new look of npm website is much better but the __leftmost link with a heart icon__ of top red ribbon containing links to pages like pricing  is broken. ( _Or maybe it is intended behavior in which case this issue can be closed._ ) It leads to a user published package instead of a welcome page for first time publishers like previous version of website

## Link to the page
Almost every page with desktop view.

## Logged in or logged out?
Both

## Expected behavior
It should show [this page](https://web.archive.org/web/20170927014915/https://www.npmjs.com/my-first-publish) like previous version of website.

## Actual behavior
It resolves to [a user published package](https://www.npmjs.com/package/my-first-publish).

## Steps to reproduce the problem
1. Go to https://www.npmjs.com from a desktop browser.
2. Click on the leftmost heart icon on the top red ribbon containing links to pages like pricing.
3. It should show a special page at `https://www.npmjs.com/my-first-publish` welcoming first time publishers but it goes to `https://www.npmjs.com/package/my-first-publish` which is a user published package.

## Browser with version

Firefox Developer Edition
v60.0b5

Safari
v11.0.3

## Any error message?
No

**Comment by jefflembeck** [comment]
Link removed, since that page has not carried over to the new site yet. Thank you!
