### ISSUE TITLE
package list pagination problems

### ISSUE THREAD

**Issue by stefee** [npm/www#351]
## Link to the page
https://www.npmjs.com/org/choojs
https://www.npmjs.com/org/choojs?perPage=40

## Logged in or logged out?
Either.

## Expected behaviour
* [x] `show more pacakges` button should only appear if there are more packages to show.
* [x] Clicking `show more packages` should load some new items onto the page that are not already there.
* [x] Appending `?perPage=` to the URL should show the specified number of packages (or all packages if the number is greater than the max).

## Actual behaviour
* ~~`show more packages` appears even when all the packages in an org are already being displayed.~~
* ~~Clicking `show more packages` loads the list of packages which is already being displayed a second time, meaning the same package list is duplicated repeatedly on the page.~~
* Appending `?perPage=` to the URL has no effect under any circumstances (as far as I can tell).

## Steps to reproduce the problem
1. Load https://www.npmjs.com/org/choojs
2. Note that there are `40` packages in this org.
3. There are currently 25 packages on the page.
4. Clicking `show more packages` loads the next 15 packages.
5. The `show more packages` button still appears, despite there being 40 packages on the page now.
6. Clicking `show more packages` now loads another 15 packages.
7. Searching (Cmd+f) for the package name at the very bottom of the page at this point shows the same package appears 3 times on the same page. [[Screenshot]](https://user-images.githubusercontent.com/18026180/37803298-e8545c06-2e25-11e8-8f59-505a1ba1651d.png)
8. Load https://www.npmjs.com/org/choojs?perPage=40
9. Only 25 packages appear on the page, not the expected 40.

## Browser with version
Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)
macOS High Sierra Version 10.13.3 (17D102)

## Any error message?
No.

**Comment by stefee** [comment]
Marking 2/3 subtasks as resolved as these appear to be fixed now! 🎉

**Comment by stefee** [comment]
@aearly The `?perPage=` issue doesn't appear to be resolved to me.

**Comment by aearly** [comment]
Try again, you tested before we deployed!
