### ISSUE TITLE
Number of issues for private repos is NaN

### ISSUE THREAD

**Issue by kmoe** [npm/www#353]
## Link to the page
https://www.npmjs.com/package/@SCOPE/REPO

## Logged in or logged out?
Logged in

## Expected behavior
Side panel on the right displays number of issues for that repo.

## Actual behavior
NaN is displayed instead:
![issuesnan](https://user-images.githubusercontent.com/5575356/37844969-36fbcfec-2ec1-11e8-91a0-5a7915ec118e.png)

## Steps to reproduce the problem
1. Log in to npmjs.com
2. Go to the page for a private repo to which you have access

## Browser with version
Chromium version 65.0.3325.162 (Developer Build) (64-bit)

## Any error message?
The console shows that an unauthenticated request is being made to https://api.github.com/repos/ORG/REPO/issues?per_page=1, which returns a 404.

**Comment by aearly** [comment]
This should be fixed!
