### ISSUE TITLE
Package details are missing crucial information

### ISSUE THREAD

**Issue by Reinmar** [npm/www#357]
## Link to the page

Eg. https://www.npmjs.com/package/@ckeditor/ckeditor5-dev-compiler?activeTab=readme

## Expected behavior

I published this package with the following readme:

```
☠ This package was removed. See https://docs.ckeditor.com/ckeditor5/latest/framework/guides/quick-start.html for how to build CKEditor 5 from source. ☠
```

And the following `package.json`:

```
{
  "name": "@ckeditor/ckeditor5-dev-compiler",
  "version": "7.0.0",
  "description": "☠ This package is not supported any more. See https://github.com/ckeditor/ckeditor5-dev/issues/268. ☠",
  "author": "CKSource (http://cksource.com/)",
  "license": "(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)",
  "homepage": "http://ckeditor.com"
}
```

All this information (the readme and pkg description), which was clearly visible on the old website, is now completely gone. I expect that this information is brought back.

## Actual behaviour

![image](https://user-images.githubusercontent.com/156149/37903428-283a2434-30f8-11e8-9661-6b61a817353d.png)

**Comment by monsterkodi** [comment]
it seems that right now *all* readmes are rendered without the topmost block of text.

it doesn't matter what you start your readme with (heading, image, text, ...) it gets ignored until the first empty line is reached. the remainder is rendered fine.  

luckily i start most of my readme's with a little icon, so this didn't occur to me first, although i had the feeling that something is slightly wrong :-)

and i think you are right, it is related to #329

**Comment by aearly** [comment]
This should be fixed.  I'd also recommend using `npm deprecate` to deprecate unmaintained/obsolete packages.
