### ISSUE TITLE
Typo @angular2-material/grid-list

### ISSUE THREAD

**Issue by christophechevalier** [npm/www#37]
Hi all ! 

When you explain how to use "md-grid-list", I found a little error on the typo of grid-list.

```
import {MdGridListModule} from '@angular2-material/gridlist/gridlist'; FALSE
import {MdGridListModule} from '@angular2-material/grid-list/grid-list'; TRUE

@NgModule({
  imports: [MdGridListModule],
  ...
})
export class MyAppModule {}
```

[https://www.npmjs.com/package/@angular2-material/grid-list](url)

Have a good day !

**Comment by micnic** [comment]
you should post this somewhere here: https://github.com/angular/material2

**Comment by ashleygwilliams** [comment]
hi @christophechevalier ! @micnic is correct- we handle the rendering of the READMEs but not their content. you should def file this as an issue on the package's repo! thanks, closing.
