### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by lieuweberg** [npm/www#372]
## Link to the page
https://www.npmjs.com/package/hubot-spotify-search // any package page

## Logged in or logged out?
Logged in

## Expected behavior
The webpage loads without having an error in the Readme

## Actual behavior
Error 503 No healthy backends
No healthy backends

Guru Mediation:
Details: cache-ams4133-AMS 1523298312 567457779

Varnish cache server

## Steps to reproduce the problem
1. Go to any package page, try to open it and else open in a new tab

## Browser with version
Google Chrome | 65.0.3325.181 64bit

## Any error message?
Error 503 No healthy backends

**Comment by larsgw** [comment]
This seems to happen on the home page (when not logged in) too...

EDIT: Actually, on basically all pages with somewhat static content (I think that's it, anyway), like https://www.npmjs.com/features and https://www.npmjs.com/pricing. When visiting those pages in the nav bar, it says "error loading page". Checking the network activity show responses like this one:

<details>
<pre>
{"undefined":true,"title":"npm features","flatpage":{"data":
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot;
 &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
&lt;html&gt;
  &lt;head&gt;
    &lt;title&gt;503 No healthy backends&lt;/title&gt;
  &lt;/head&gt;
  &lt;body&gt;
    &lt;h1&gt;Error 503 No healthy backends&lt;/h1&gt;
    &lt;p&gt;No healthy backends&lt;/p&gt;
    &lt;h3&gt;Guru Mediation:&lt;/h3&gt;
    &lt;p&gt;Details: cache-ams4148-AMS 1523302072 3820226169&lt;/p&gt;
    &lt;hr&gt;
    &lt;p&gt;Varnish cache server&lt;/p&gt;
  &lt;/body&gt;
&lt;/html&gt;
,"ref":"flatpage"},"documentContext":{"flatpage.data":"flatpage"},"user":{"tfa":false,"name":"larsgw","email":"lars.willighagen@gmail.com","avatars":{"small":"https://s.gravatar.com/avatar/01ffe58fdc68c3fa14fb0de3c0d06c97?size=50&default=retro","medium":"https://s.gravatar.com/avatar/01ffe58fdc68c3fa14fb0de3c0d06c97?size=100&default=retro","large":"https://s.gravatar.com/avatar/01ffe58fdc68c3fa14fb0de3c0d06c97?size=496&default=retro"},"resource":{"step3":"1","github":"larsgw","twitter":"larswillighagen","fullname":"Lars Willighagen","homepage":"https://larsgw.github.io"},"email_verified":true,"created":"2016-10-27T10:10:20.338Z","updated":"2017-08-31T09:50:59.047Z"},"csrftoken":"fBx92Gb3au68PbPgwpfLtnC0z07-2Ap-EAua0rjLGdl","notifications":[],"npmExpansions":["Naming Prosecution Mitigator","Never Push to Master","Node Promiscuous Modules","Narrating Prophetic Monks","Newly Practicing Mortician","New Prog Mixtape","Nihilist Pocket Monsters","Needlessly Provoking Marsupials","Nebulous Plasma Muffin","Nearly-Pickled Module"]}
</pre>
</details>

---

EDIT 2: The site does work for me when using a UK VPN.
EDIT 3: Works normally for me again.

**Comment by jefflembeck** [comment]
Looks like this was a problem with some specific locations. Thanks for letting us know. It's been resolved now.
