### ISSUE TITLE
question: what happened to stars?

### ISSUE THREAD

**Issue by knksmith57** [npm/www#375]
## Link to the page
* example package page: https://www.npmjs.com/package/lodash
* my profile page: https://www.npmjs.com/settings/knksmith57/profile

## Logged in or logged out?
logged in

## Expected behavior
1. package pages have a clickable star to allow logged-in users to star/unstar packages
2. somewhere under profile a logged-in user can see their starred packages

## Actual behavior
stars appear to have entirely disappeared from the web UI.

<details>

<summary>
note that I have previously starred packages via the website and can confirmed that my account has starred packages by executing <code>npm stars</code> from the CLI while logged in, eg:
</summary>

```
❯ npm whoami
knksmith57

❯ npm stars
@retailmenot/common-handlebars-helpers
@retailmenot/roux
@std/esm
appmetrics.js
async-tracer
bigrig
bitbucket-server-nodejs
cardinal
casual
changes-stream
chrome-launcher
classnames
cli-highlight
clone
console.table
cosmiconfig
create-error-class
easy-table
es6-promise
express-ipfilter
express-route-builder
faucet
from2
got
grpc
hippie-swagger
httpism
hyperquest
jira-connector
lerna
local-npm
marky-markdown
meow
micron
netrc
node-forge
normalize-package-data
npm-package-arg
nunjucks
once
openid-client
personalcapital-js
pino-debug
pkg
popsicle
react-google-recaptcha
react-loadable
remark
retry
runjs
semantic-release
source-map-explorer
spoof
stoppable
swagger-express-middleware
tap
teamcity-service-messages
toobusy-js
unified
useragent
whatwg-fetch
```

</details>

## Steps to reproduce the problem
1. visit www.npmjs.com
2. log in
3. navigate to any package page (eg: https://www.npmjs.com/package/lodash)
4. observe that there is no clickable star
5. navigate to profile page @ https://www.npmjs.com/settings/knksmith57/profile
6. observe that there is no list of starred packages

## Browser with version
Google Chrome 65.0.3325.181 (Official Build) (64-bit)

## Any error message?
no

**Comment by jefflembeck** [comment]
@knksmith57 Real answer: we're rewriting the way it works for the current website. It might take a couple of months. The underlying service that it was using had some pretty severe problems and needed to be retired.

**Comment by knksmith57** [comment]
cool, appreciate your candor! fwiw +1 from me on bringing it back 😘
