### ISSUE TITLE
Typo on home page: JQuery -> jQuery

### ISSUE THREAD

**Issue by kborchers** [npm/www#379]
## Link to the page
https://www.npmjs.com/

## Logged in or logged out?
either

## Expected behavior
jQuery should have a lowercase j

## Actual behavior
jQuery is currently spelled with an uppercase J

## Steps to reproduce the problem
1. Open the page and scroll to "What can you make..." section and look under "Find"

## Browser with version
Chrome 65.0.3325.181

## Any error message?
No

**Comment by kborchers** [comment]
This is obviously a minor issue but a fix would be very much appreciated! ❤️

**Comment by jefflembeck** [comment]
Fixed, thanks!
