### ISSUE TITLE
Package version in search list is different from the detail page.

### ISSUE THREAD

**Issue by HJava** [npm/www#388]
## Link to the page
search list: https://www.npmjs.com/search?q=npm
detail page: https://www.npmjs.com/package/npm
## Logged in or logged out?
logged out
## Expected behavior
Two pages have the same version.
## Actual behavior
Two pages have the different version.
## Steps to reproduce the problem
1. open npmjs.com
2. search npm
3. click the first result

## Browser with version
chrome 66.0.3359.117
## Any error message?

![image](https://user-images.githubusercontent.com/3412268/39177117-073db7f0-47e1-11e8-89f3-f1514746c860.png)

![image](https://user-images.githubusercontent.com/3412268/39177139-12252694-47e1-11e8-943f-09a69377c984.png)

**Comment by dhershman1** [comment]
Looks like it's the same for your package list if you have published recently on your list you still see old versions vs the details page being current.

**Comment by nickserv** [comment]
I am noticing this in all search results.

**Comment by kroltan** [comment]
Observed: Typescript 2.7.2 (2 months ago's release) in search page, 2.8.3 in details page.

Not only that, but there have been tens of releases since then. So it hasn't been updated since the following time range:

From 15/02/2018, 16:45:13 to 16/02/2018, 04:42:07

**Comment by jefflembeck** [comment]
There are a few different issues that are going on here.

1. Our search analyzer and follower was running a little slowly. This can result in updating taking a little longer. This _should_ be resolved now.

2. There is an issue in the analyzer with size of repo and amount of files. I've opened an issue here to address this: https://github.com/npms-io/npms-analyzer/issues/215
