### ISSUE TITLE
the behavior of README taken from GitHub is bad

### ISSUE THREAD

**Issue by zhanzhenzhen** [npm/www#391]
Think of this scenario:

One have a public package, but the source code is in a private repo on GitHub, only the "obfuscated and minified" version is public in npm. But in the current implementation of your website, it seems README is taken from GitHub rather than from the package itself! For example, I have such a package and it says it doesn't have a readme file, maybe just because it can't access my GitHub repo.

Also, using GitHub makes README inaccurate. GitHub's README may change over time. It reflects the state of the master branch, not of the current version.

**Comment by jefflembeck** [comment]
@zhanzhenzhen the README is not taken from GitHub. The README is taken from the package itself upon publication. We show the README of the package version that is tagged `@latest`.

**Comment by zhanzhenzhen** [comment]
Thank you for clarifying. I now find my README is shown in npmjs. Very weird. Maybe yesterday something went wrong.

**Comment by hodgef** [comment]
I had the same issue and had posted to https://github.com/npm/npm/issues/20469 about it. The readme parsing was bugged but then fixed shortly.
