### ISSUE TITLE
Internal error on package description page

### ISSUE THREAD

**Issue by gtsiam** [npm/www#393]
Link: [neo4j-driver](https://www.npmjs.com/package/neo4j-driver)

I tried loading the description page for the neo4j-driver, but got this:

> {"code":"Internal","message":"caused by InvalidParameterType: Expected params.IfModifiedSince to be a Date object, ISO-8601 string, or a UNIX timestamp"}

It might be noteworthy that at the time this happened, the packaged had been updated 4 hours ago, as this error does not appear when loading other packages (And that is clearly not the github readme). 

Also the console shows no errors, so it probably happened somewhere on the server.

Tested (Logged out) with Firefox 59.01 & Chromium 63.0.3239.108

**Comment by Sonic12040** [comment]
This is showing for me with no console errors as well, across multiple packages such as inquirer and mysql (tested).

Tested with Firefox 59.0.3 and Microsoft Edge 41.16299.371.0.

**Comment by elias6** [comment]
This is happening for me on https://www.npmjs.com/package/wrapper-webpack-plugin. It was working maybe 20 minutes ago, but it is not now.

**Comment by Alan-Liang** [comment]
It happened on https://www.npmjs.com/package/debug a few seconds ago, but not now. I am using chrome android 66.0.3359.126. The package is last updated 7 months ago.

**Comment by DavidChipman** [comment]
I''m seeing the error on https://www.npmjs.com/package/xpm. Given all the other messages on here, is the whole site affected?

**Comment by gtsiam** [comment]
I just checked again, and it didn't happen with [neo4j-driver](https://www.npmjs.com/package/neo4j-driver) (It's now 18 hours since last update, and some of the packages haven't been updated in months, so it probably doesn't have to do with the time since it was last updated)

But after a few reloads, it happened again. I also managed to get it with express, so it probably isn't package-dependant. so... maybe a race condition?

**Comment by two-bridges** [comment]
I'm seeing an error on 
https://www.npmjs.com/package/angular-ui-sortable 

The Readme text has been replaced with:
[object Object]

Doesn't match the OP's exact error, but timing is suspicious

**Comment by gtsiam** [comment]
I actually got that on a few of the reloads, but it was far less reproducible than the error I mentioned. Could be related, but I can't know.

**Comment by shannonmoeller** [comment]
Seeing this error as well.

http://npm.im/serve
http://npm.im/livery

```
{"code":"Internal","message":"caused by InvalidParameterType: Expected params.IfModifiedSince to be a Date object, ISO-8601 string, or a UNIX timestamp"}
```

**Comment by VMois** [comment]
When you open description of the package first time this error doesn't appear, but when you open second time this error appears every time. I think it is a problem with ifmodified header format. It is not proper and server returns error.

**Comment by jefflembeck** [comment]
Hey all, unfortunately this was a known issue with our readme and caching services. We've put a fix in and are working on re-rendering all of the package readmes. This unfortunately will take a bit, so if you continue to see this error, let us know and we'll take care of it.
