### ISSUE TITLE
ISC license displaying on npm, but have MIT license in repo

### ISSUE THREAD

**Issue by melanieseltzer** [npm/www#396]
I'm not sure why this is happening as I definitely have MIT in my repo. Also installed the package as a dependency for testing, and the license is there and it's MIT.

## Link to the page

https://www.npmjs.com/package/grammarize
https://github.com/melanieseltzer/grammarize/blob/master/LICENSE

## Logged in or logged out?

Both.

## Expected behavior

Display 'MIT' under license heading on my package page.

## Actual behavior

'ISC' shows instead.

## Steps to reproduce the problem

Look at package page under license heading.

## Browser with version

N/A

## Any error message?

N/A

**Comment by jefflembeck** [comment]
@melanieseltzer we read your license type from the package.json file, https://github.com/melanieseltzer/grammarize/blob/master/package.json#L31

See: https://docs.npmjs.com/files/package.json#license for options (you'll likely want: 'MIT' as the value there)

**Comment by melanieseltzer** [comment]
Whoops! Thanks for the clarification 😄
