### ISSUE TITLE
Feature request: show dependents count

### ISSUE THREAD

**Issue by mscdex** [npm/www#40]
It would be nice to see a dependents count on individual module pages, much like the dependencies count that already exists.

**Comment by aredridel** [comment]
We should totally do that! Adding that to our list of coming feature work.

**Comment by mscdex** [comment]
@aredridel I'm confused, why was this closed? There still is no count visible on npmjs.com? Was this feature request rejected?

**Comment by jefflembeck** [comment]
@mscdex ah! It was closed automatically by GitHub because of their "fixes __" shortcut. This has made its way into master in our codebase so should see the light of day very very soon. Thank you!

**Comment by aredridel** [comment]
Agh, yeah. Sorry about that!
