### ISSUE TITLE
Impossible to reach the package by searching for it in the web (but it is available via URL).

### ISSUE THREAD

**Issue by allnulled** [npm/www#404]
## Link to the page

[https://www.npmjs.com/search?q=web2os](https://www.npmjs.com/search?q=web2os)

## Logged in or logged out?

Both.

## Expected behavior

To see the [web2os](https://www.npmjs.com/package/web2os) package listed among the packages found.

## Actual behavior

The [web2os](https://www.npmjs.com/package/web2os) package does **not** appear in the list of **packages found**.

## Steps to reproduce the problem

1. Go to the [NPM main page](https://www.npmjs.com/).

2. Search in the text box for: **web2os**.

3. Click [ENTER].

4. Check the listed **found packages**.

(Or directly, visit the [first link](https://www.npmjs.com/search?q=web2os) provided in the issue, which does these steps by querystring parameters)

*Note: I have noticed that the package is found when I search for it from the [npms repository](https://npms.io/search?q=web2os), but not when I search for it from the [npm repository](https://www.npmjs.com/search?q=web2os).*

## Browser with version

Google Chrome 66.0.3359.139.

## Any error message?

None.

**Comment by bazmatic** [comment]
I'm seeing exactly the same issue for `ipfs-image-drop`.

**Comment by bazmatic** [comment]
I can't resist pointing out that this issue, which is about packages not being found, is number 404.  :-)

**Comment by allnulled** [comment]
It seems that the problem was solved! Thank you!
