### ISSUE TITLE
Unicode is broken

### ISSUE THREAD

**Issue by yentsun** [npm/www#405]
## Link to the page

Any package with unicode text

## Logged in or logged out?

Both

## Expected behavior

```
Kōjō (工場) means 'factory' in Japanese.
```

## Actual behavior

```
KĹjĹ (ĺˇĽĺ ´) means 'factory' in Japanese.
```

## Steps to reproduce the problem

Visit https://www.npmjs.com/package/kojo or any other package with unicode in description

## Browser with version

```
Google Chrome
Version 66.0.3359.139 (Official Build) (64-bit)
```

## Any error message?

Nope

**Comment by yentsun** [comment]
Related: https://github.com/npm/www/issues/398

**Comment by jefflembeck** [comment]
This issue has been fixed. Thank you!
