### ISSUE TITLE
  Version cannot be updated

### ISSUE THREAD

**Issue by BlackHole1** [npm/www#406]
## Link to the page
https://www.npmjs.com/package/run-objfun

## Logged in or logged out?
Logged in

## Expected behavior
The version on NPM should be 1.0.6

## Actual behavior
There is no change in the version, Open npmjs.com, version is 1.0.5. 

When I used `npm publish`, the terminal was wrong:

![default](https://user-images.githubusercontent.com/8198408/39882085-712ec6f0-54b5-11e8-982c-3df069ab2fe3.png)

![default](https://user-images.githubusercontent.com/8198408/39882120-8253fe00-54b5-11e8-9f9a-1b206fb4af8e.png)

## Steps to reproduce the problem
1. Update your npm package
2. open npmjs.com
3. There is no change in the version
4. amazing!  

## Browser with version
node version: `8.9.4`
npm version: `6.0.0`
os: `win10`

## Any error message?
![default](https://user-images.githubusercontent.com/8198408/39882085-712ec6f0-54b5-11e8-982c-3df069ab2fe3.png)

![default](https://user-images.githubusercontent.com/8198408/39882120-8253fe00-54b5-11e8-9f9a-1b206fb4af8e.png)

**Comment by madelk** [comment]
I was having the same issue and it just suddenly resolved itself

**Comment by MunifTanjim** [comment]
Same issue with https://www.npmjs.com/package/bkash

Published `0.2.0` & `0.2.1`. But npmjs.com is stuck on `0.1.1`.
