### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by EasonWang01** [npm/www#413]
https://github.com/npm/npm/issues/20625#issuecomment-389294233

**Comment by jefflembeck** [comment]
@easonwang01 sorry this is happening! Can you email support@npmjs.com?

One of our folks there should be able to help!

**Comment by EasonWang01** [comment]
I already send many email for these four month but no response.
Trying clean cookies and using incognito but still the same result.

**Comment by jefflembeck** [comment]
I’m sorry to hear that. Can you try again? Which email are you sending the message from?

**Comment by EasonWang01** [comment]
It was replied by Elizabeth. The email always asks me to clean cookies.
But still the same.

**Comment by AxelPeter** [comment]
Hi,
Same problem for me here. I can't reset my password.
The link provided with the mail lead to a 404.

I tried to clean cookies, change browsers, incognito mode. It's the same issue.

**Comment by EasonWang01** [comment]
And I also found my organization has been deleted.


@ Elizabeth send me email told me to log out again, but I do it already, does she is a robot?

**Comment by ludofischer** [comment]
Did anyone manage to find a solution for this? I am suffering from the same issue. No reply from support since Sunday.

**Comment by ludofischer** [comment]
I managed to get the reset password flow to work by visiting the reset password link in Firefox with the developer tools open, strangely enough.

**Comment by EasonWang01** [comment]
It gives me `{"message":"Too Many Requests","requestID":"+u0KZ+CCRYil+11Ck2wZAg=="}` on Firefox developer version and Safari.

**Comment by kmiasko** [comment]
Same issue. After first try i've go Too Many Requests response, second time 404 error.

**Comment by EasonWang01** [comment]
After 13 days, Elizabeth send me another email this morning then I restart my computer. Now I'm able to change the password.

**Comment by enyachoke** [comment]
Hi guys thanks for the good work. This seems like something that needs fixing am also getting a 404 when trying to reset my password. Just sent an email to support though.
