### ISSUE TITLE
www.npmjs.com unavailable in Russia

### ISSUE THREAD

**Issue by sheershoff** [npm/www#414]
## Link to the page
https://www.npmjs.com/

## Logged in or logged out?
either

## Expected behavior
the page opens

## Actual behavior
ERR_CONNECTION_RESET

## Steps to reproduce the problem
1. Try to open the site from Russia based internet provider
2. Fail
3. check `host www.npmjs.com`:
```
$ host www.npmjs.com        
www.npmjs.com is an alias for www.npmjs.com.cdn.cloudflare.net.
www.npmjs.com.cdn.cloudflare.net has address 104.16.110.30
www.npmjs.com.cdn.cloudflare.net has address 104.16.109.30
```
4. see that both IPs are blocked in Russia since 2016 at page https://eais.rkn.gov.ru/

## Browser with version
any

## Any error message?
ERR_CONNECTION_RESET

**Comment by sheershoff** [comment]
IPs are not in the blocked list anymore

**Comment by eahefnawy** [comment]
As of today, it is on the list 😒 
<img width="902" alt="screen shot 2018-06-11 at 3 35 14 pm" src="https://user-images.githubusercontent.com/2312463/41233384-f566ee30-6d91-11e8-9417-1e87a65cddca.png">
