### ISSUE TITLE
Downloads per week counter is broken

### ISSUE THREAD

**Issue by robcresswell** [npm/www#424]
I checked my little side project and noticed the downloads per week had fallen from something like 1500 to 30; no big deal, its just a utility. Then I checked Vue and React, clearly major projects, and both of their downloads have also fallen off a cliff. Has some new caching mechanism come come online and stopped things being counted correctly? Or is the counter not working at all? 

For reference:
- https://www.npmjs.com/package/react
- https://www.npmjs.com/package/vue

**Comment by Reinmar** [comment]
Noticed that too (e.g. here https://www.npmjs.com/package/@ckeditor/ckeditor5-editor-classic).

**Comment by Reinmar** [comment]
It's yet another issue in the last two weeks ;/ None of the issues was a complete disaster itself, but the frequency of them and little (or zero) response from your side leaves a terrible impression.

First, the registry [went down](https://github.com/npm/registry/issues/324). Then, [readmes disappeared](https://github.com/npm/www/issues/418). Now, another issue.

**Comment by hodgef** [comment]
There's definitely an issue with the download counts. React for example currently shows just 6 downloads/week. I think the npm team should be more communicative about maintenance changes. They must have noticed this problem already yet we haven't heard back. They should definitely monitor the issue tracker more closely and not just the support email.

![issue](https://user-images.githubusercontent.com/25509135/40975089-c2c000d8-6897-11e8-9e26-576e16ea944a.png)

**Comment by hodgef** [comment]
It seems npm has acknowledged the issue here: https://status.npmjs.org/incidents/b4ktc38pypd1
via @npmstatus on Twitter

**Comment by jwalton** [comment]
They added CloudFlare as a cache in front of the registry.  This was the cause of most of the issues over the past few weeks, and I'm guessing is this cause of this also.  There was a very interesting thread about this [from one of the Yarn guys here](https://twitter.com/jamiebuilds/status/1000198463269699584).

**Comment by Reinmar** [comment]
This issue can be closed now.

**Comment by robcresswell** [comment]
Appears to be solved now. Unfortunately looks like the data couldn't be retroactively reclaimed, but I guess we'll keep that as the week that every web developer in the world took some holiday 😄

**Comment by atomiks** [comment]
I think it's broken again.
