### ISSUE TITLE
account requires first and last name, culturally insensitive

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/www#44]
<img width="670" alt="screen shot 2016-10-05 at 5 47 30 pm" src="https://cloud.githubusercontent.com/assets/1163554/19132933/e506dfd4-8b23-11e6-8eb6-bf2099285b37.png">

many cultures do not have this name construction, and also this name construction does not afford us any value. it should be a single field with little validation. 

a good read: https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by ashleygwilliams** [comment]
fyi, GitHub does not require first and last name. in fact it doesn't require a name At All.

<img width="754" alt="screen shot 2016-10-05 at 6 25 08 pm" src="https://cloud.githubusercontent.com/assets/1163554/19133968/1d702d08-8b29-11e6-97b7-9bd775a0d098.png">

**Comment by aredridel** [comment]
Fixed.
