### ISSUE TITLE
Home page link url is incorrect

### ISSUE THREAD

**Issue by Sandeepv68** [npm/www#456]
## Link to the page
All packages have this issue.
https://www.npmjs.com/package/blocktron-lib

## Logged in or logged out?
both

## Expected behavior
Supposed to be linking to the proper readme files or github pages

## Actual behavior
Link is broken 

## Browser with version
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by iarna** [comment]
Further discussion: https://npm.community/t/npm-website-link-to-a-packages-homepage-is-being-generated-incorrectly-for-github-links/344

But TLDR, my bad, fix should be deployed today.

**Comment by Sandeepv68** [comment]
Thank you @iarna for fixing this soon.
