### ISSUE TITLE
Keywords are not represented in regular search queries

### ISSUE THREAD

**Issue by alexhultman** [npm/www#48]
![screencapture-npmjs-search-1476332621005](https://cloud.githubusercontent.com/assets/3397140/19336719/05ab8f1a-910e-11e6-9a3b-015c680c4bfa.png)

**Comment by alexhultman** [comment]
![screencapture-npmjs-search-1476333032445](https://cloud.githubusercontent.com/assets/3397140/19336793/a405824c-910e-11e6-8148-233b60e17d2b.png)

**Comment by alexhultman** [comment]
Like, what is the point exactly with adding keywords when they don't work in any way whatsoever?

**Comment by jefflembeck** [comment]
Hi, sorry about your experience. We know the search needs to be worked on and we promise that it’s on our roadmap. Thanks for taking the time to fill an issue!
