### ISSUE TITLE
Bad image rendering in Markdown header

### ISSUE THREAD

**Issue by dandv** [npm/www#49]
https://www.npmjs.com/package/socket.io-client

![image](https://cloud.githubusercontent.com/assets/33569/19338344/4d4d1d8a-90d1-11e6-970a-1735eb36db41.png)

**Comment by aredridel** [comment]
Thanks for the report! That's certainly not good. We've added it to our internal bug tracker and will try to get that fixed!

**Comment by ashleygwilliams** [comment]
closing in favor of https://github.com/npm/registry/issues/68
