### ISSUE TITLE
Provide node.js version usage along with download counts

### ISSUE THREAD

**Issue by analog-nico** [npm/www#50]
Package maintainers currently have to guess on which node.js versions (engine versions) their packages are installed. So their decision to keep supporting e.g. node v0.10 or move up to a newer version is also based on guesswork. Likely, many packages are moving towards `node >= 4` in order to make use of the new ES6 features and at the same time enterprise apps in particular loose support. As you can see [in this article](https://semaphoreci.com/blog/2016/10/12/nodejs-versions-used-in-commercial-projects-2016-edition.html) old node.js versions are still heavily used.

It would be great if npm would track the node.js versions a package gets installed into. Then showing these statistics on the npm website along with the download counts would be really helpful.

engine | downloads last day | downloads last week | downloads last month
------ | ------------------ | ------------------- | --------------------
node v0.10 | 20 | 140 | 600
node v0.11 | 1 | 14 | 56
node v0.12 | 40 | 280 | 1200
io.js v3 | 4 | 10 | 42
node v4 | 120 | 801 | 3109
node v5 | 23 | 150 | 712
node v6 | 102 | 725 | 3005

IMHO this would be a feature that will contribute to the healthy package ecosystem.

**Comment by aredridel** [comment]
This is actually something that will need support from [the registry](https://github.com/npm/registry) in addition to being made visible on the web site. It would indeed be useful, but any work will have to start there.
