### ISSUE TITLE
Visual misalignment in enterprise plans

### ISSUE THREAD

**Issue by thomblake** [npm/www#55]
Don't know if this is on purpose...

Mac OS Sierra, Chrome 54.0.2840.71 (64-bit)

<img width="996" alt="screen shot 2016-10-26 at 11 29 30 am" src="https://cloud.githubusercontent.com/assets/55923/19739474/e9a9704a-9b6f-11e6-8ce4-0a9eed7eeab5.png">

**Comment by aredridel** [comment]
Thanks for this! We should have a fix for this out soon.

**Comment by cowperthwait** [comment]
NB @aredridel, [Inconsistent vertical alignment of pricing boxes #717](https://github.com/npm/npm-website/issues/717) actually flags the same behavior on a different page — but I assume this issue refers to the underlying problem responsible for both.

**Comment by aredridel** [comment]
Oh so it does! But yes, same approach will solve both

**Comment by ashleygwilliams** [comment]
we've filed this on our internal bug tracker. thanks so much for filing!
