### ISSUE TITLE
Website drops last path segment in repository url for monorepos

### ISSUE THREAD

**Issue by ianwremmel** [npm/www#56]
The repository link at https://www.npmjs.com/package/ciscospark points to https://github.com/ciscospark/spark-js-sdk/blob/master/packages but the corresponding package.json points to https://github.com/ciscospark/spark-js-sdk/blob/master/packages/ciscospark.

**Comment by aredridel** [comment]
Interesting! Looks like the heuristics in https://github.com/zeke/github-url-to-object fail you.

What information are you trying to communicate to users? There's not exactly a standard for how to communicate a subtree of a repo for cloning and/or viewing, so this is wandering into kinda undefined territory. I'm going to close this issue, as it would be more appropriately opened on https://github.com/zeke/github-url-to-object

**Comment by ianwremmel** [comment]
I'm following the lerna monorepo pattern used by babel and i expected the repo url to point people to the correct readme and subtree.

**Comment by zeke** [comment]
Not sure what version of `github-url-to-object` the npm website is using as it's no longer an open-source project, but FWIW a PR was landed recently to support "lerna-style" repositories.

See https://github.com/zeke/github-url-to-object/pull/24

That fix is available as of `github-url-to-object@2.2.5`

**Comment by ianwremmel** [comment]
@aredridel, can this issue be reopened since @zeke says it's solved in github-url-to-object?

**Comment by aredridel** [comment]
Will update.
