### ISSUE TITLE
Allow viewing a list of all releases of a particular package

### ISSUE THREAD

**Issue by Ajedi32** [npm/www#57]
Currently it's only possible to see the version number of the latest release of a package from the NPM website:

![2.3.0 is the latest of 41 releases](https://cloud.githubusercontent.com/assets/1876931/19984863/2c61d304-a1de-11e6-961e-debbf6e21419.png)

It'd be great if we could click on "41 releases" to see a list of all releases, along with the date they were published, their [associated tags](https://docs.npmjs.com/cli/dist-tag), and their [deprecated status](https://docs.npmjs.com/cli/deprecate).

**Comment by Ajedi32** [comment]
See also #13 and [How to see package history?](http://stackoverflow.com/q/14982502/1157054) (Which implies this is a rather common issue people are experiencing.

**Comment by aredridel** [comment]
Definitely! We'll pass this on to product folks for when we work on package pages next!
