### ISSUE TITLE
chrome font not monospaced, causes whitespace in <pre> to render incorrectly

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/www#59]
from @lewiscowper via https://github.com/npm/marky-markdown/issues/284

> There's a noticeable difference in rendering between how marky-markdown and github renders whitespace in `<pre>` tags.
>
> ![screen shot 2016-11-03 at 23 00 36](https://cloud.githubusercontent.com/assets/593574/19987034/62d9852c-a219-11e6-9127-510515cd0256.png)
>
> vs:
>
> ![screen shot 2016-11-03 at 23 01 06](https://cloud.githubusercontent.com/assets/593574/19987063/8682ec16-a219-11e6-80b3-609021badaf9.png)
>
> If I can get `marky-compare` fixed then I can easily attach a diff to this issue.

from @revin
> Is there any chance this is the font choice on npmjs.com? In Brave on my mac, it renders as expected on npmjs.com/package/boxen, but on Chrome it appears as in your first screenshot; however, if I set, e.g., font-family: 'courier new' in Dev Tools, everything lines up. The Sources tab seems to indicate that each line is 15 characters long in the generated markup.

**Comment by oskarhane** [comment]
+1 on fixing this, it makes my package appear broken.

https://www.npmjs.com/package/ascii-data-table
vs
https://github.com/oskarhane/ascii-data-table

**Comment by ashleygwilliams** [comment]
just merged my fix for this! should hopefully be live soon :) closing

**Comment by e02d96ec16** [comment]
May I have _Consolas_ instead of _Courier New_ please?
