### ISSUE TITLE
`stats` in the sidebar points to the wrong repository

### ISSUE THREAD

**Issue by kudrykv** [npm/www#60]
As the example:
https://www.npmjs.com/package/recurly-js

Links are going to the base repository, not to the forked one.

**Comment by marcbachmann** [comment]
The url is fetched from the repository field in the package.json. https://docs.npmjs.com/files/package.json#repository
I guess that was outdated in that fork. It got fixed in the meanwhile.
![image](https://cloud.githubusercontent.com/assets/431376/20450448/025e9abe-adf1-11e6-874a-aab4c8b7fbc8.png)

**Comment by aredridel** [comment]
What repo should it be going to instead?

Your package.json as the registry knows it is 

```
 repository:
   { type: 'git',
     url: 'git+https://github.com/umayr/recurly-js.git' },```

**Comment by jefflembeck** [comment]
Thanks @marcbachmann , looks like this is fixed then? Closing (reopen if I totally misunderstood you there)

**Comment by marcbachmann** [comment]
yep, shouldn't be a problem on your side. the fork just didn't update the repo link in the package.json.
