### ISSUE TITLE
npm ticker glitch

### ISSUE THREAD

**Issue by jdalton** [npm/www#62]
![](https://cloud.githubusercontent.com/assets/4303/20154377/d9e9ba18-a67b-11e6-9fa7-4b7bdc06f89e.gif)

**Comment by jdalton** [comment]
I'm still seeing the glitch. It comes down to a bug in the static/js/index.min.js:
```js
.type("react.692571ab").pause(n).delete(5)
```

**Comment by jdalton** [comment]
It looks like it could be related to whatever process you have to rev resources for cache bashing.

**Comment by jefflembeck** [comment]
Sorry @jdalton, auto-fixed by GH. It's still a bug on production, it's just fixed in master for us.

**Comment by jefflembeck** [comment]
Now it's in prod. Thanks!

**Comment by jdalton** [comment]
:metal: Thank you!
