### ISSUE TITLE
automatically fetched image is too large

### ISSUE THREAD

**Issue by stianjensen** [npm/www#63]
In addition to the README.md, npmjs seem to automatically fetch an image to display.
This image has no max-width, causing it to break the layout if the size of the image is too big.

Example:
<img width="1158" alt="screenshot 2016-11-13 01 43 43" src="https://cloud.githubusercontent.com/assets/1413267/20242973/ce1a5944-a942-11e6-8477-73adaa1d6633.png">

**Comment by ashleygwilliams** [comment]
we've added this to our internal issue tracker! thank you so much filing.
