### ISSUE TITLE
unstarring https://www.npmjs.com/package/npm from npmjs.com account impossible

### ISSUE THREAD

**Issue by logol** [npm/www#64]
Hey,

is it intended that removing the star from (https://www.npmjs.com/package/npm) is impossible?

Upon clicking on the star an error is thrown

> https://www.npmjs.com/static/js/index.min.js?last-changed=c1f6b6045a26977ba29eba9d56a151e3:6 POST https://www.npmjs.com/star 500 (Internal Server Error)send @ index.min.js?last-changed=c1f6b60…:6ajax @ index.min.js?last-changed=c1f6b60…:5r.onChange @ index.min.js?last-changed=c1f6b60…:2dispatch @ index.min.js?last-changed=c1f6b60…:5g.handle @ index.min.js?last-changed=c1f6b60…:5

I also tried:

`npm unstar npm`

but that also returns an error

> error 404 Registry returned 404 for PUT on https://registry.npmjs.org/npm

**Comment by ashleygwilliams** [comment]
hi! thanks for filing- i tried to replicate this with my own account and can't... are you seeing any other errors from the website or the registry, e.g. can you login? npm publish? star/unstar other packages? i think this is a registry issue, potentially location specific! if you could let me know if you can perform the functions i listed previously as well as your location we can try to debug this! also feel free to message support@npmjs.com

**Comment by logol** [comment]
Hey,

login works normally (cli & website), my location is Germany.
npm unstar/star other packages works normally (using npm cli or website)

Website doesnt show any errors, but if I reload the page the star is present again on the npm package, so I opened the console and realized there was an POST error in index.min.js on line 7776: s.send(t.hasContent && t.data || null ) -> Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Regarding the cli `npm unstar npm` I attached the npm-debug.log as gist (https://gist.github.com/logol/3ec53c8ed36e666a595e874551a5990a)

**Comment by logol** [comment]
support@npmjs.com confirmed that it is an registry issue and asked me to open an [issue there](https://github.com/npm/registry/issues/88), so I will close this here

**Comment by mikanga10** [comment]
good networking 2018
