### ISSUE TITLE
Star count of module does not work

### ISSUE THREAD

**Issue by marcbachmann** [npm/www#67]
I have a few modules and most of them show me the same number of stars in the search result list.
This can't be right. I guess there's a query bug somewhere.

![image](https://cloud.githubusercontent.com/assets/431376/20450738/0fe84dfe-adf3-11e6-9129-2a45c37e4dd4.png)
![image](https://cloud.githubusercontent.com/assets/431376/20450518/7a974f80-adf1-11e6-8140-21fda90301ed.png)
![image](https://cloud.githubusercontent.com/assets/431376/20450528/8761a148-adf1-11e6-8e13-825889411e21.png)

**Comment by Splact** [comment]
This happened to me too. In few hours after publish my package has 50 stars and 10 downloads. Sounds a little bit optimistic 😃

**Comment by Polarisation** [comment]
I also noticed this, the star count appears to make little sense. I published a module this week, it instantly had 59 stars. And even the most popular modules do not have over 100 stars.

**Comment by Splact** [comment]
Yeah, no one use the npm star system 😄

**Comment by jefflembeck** [comment]
Good catch! yeah, our stars on the search page don't correlate to star counts currently. We know this is confusing but are rolling out new designs and work in the near future to make things more cohesive.
