### ISSUE TITLE
Problems with statistic due to letter case

### ISSUE THREAD

**Issue by 1001v** [npm/www#68]
Hello. I've published a package named [Range.js](https://www.npmjs.com/package/Range.js), but i've got statistic for it from another package named [range.js](https://www.npmjs.com/package/range.js). I mean, this two packages now have common statistic. It seems like problem somethere in sql syntax, but that's just a supposition. Thank you.

**Comment by 1001v** [comment]
I believe (that)[https://github.com/npm/www/issues/65] is the same issue, didn't noticed it, sorry. Probably, we should close this one then.

**Comment by aredridel** [comment]
Duplicate of https://github.com/npm/registry/issues/38
