### ISSUE TITLE
i cannot open the website any more

### ISSUE THREAD

**Issue by liusir0215** [npm/www#69]
1479713721259:www-14-west.internal.npmjs.com:3378:ivmp38i9:82078

**Comment by aredridel** [comment]
Looks like a bad session cookie -- try deleting the cookies for npmjs.com in your browser.

**Comment by jefflembeck** [comment]
@liusir0215 are you using Opera, perchance?

**Comment by mk-pmb** [comment]
In case of a bad session cookie, the website should at least offer a logout button. Or arrange for the logout and show itself in guest view, optionally including the error message.

**Comment by aredridel** [comment]
Indeed it should. however, not knowing what bug is triggering that, it'll be somewhat tricky to fix. 

Did clearing the session cookie fix it?

**Comment by aredridel** [comment]
No response, closing.
