### ISSUE TITLE
Error during payment

### ISSUE THREAD

**Issue by loganvolkers** [npm/www#74]
I got this error while trying to buy an organization plan.

1479924277419:www-14-west.internal.npmjs.com:3378:ivmp38i9:73843

**Comment by jefflembeck** [comment]
@loganvolkers Hey, really sorry to hear about this. Looks like an error on our billing end.

If you haven't yet, please reach out to our support team (support@npmjs.com) and they should be able to get right on that.

Thank you!

**Comment by loganvolkers** [comment]
Thanks Jeff, turns out it was a type-o in the billing details. All fixed!
