### ISSUE TITLE
Header image in README is displayed twice on npm

### ISSUE THREAD

**Issue by SoullessWaffle** [npm/www#77]
Hey, I noticed this issue when I published my module.

On my _vakt_ package page: https://www.npmjs.com/package/vakt
![vakt example](http://puu.sh/syXZm/90ca85ac94.png)

On the _yarn_ package page: https://www.npmjs.com/package/yarnpkg
![yarn example](http://puu.sh/syXUm/c628739e28.png)

This does not happen on GitHub, and there is definitely only one image in the README file.

If you look at the HTML it seems to place the duplicate header just outside the `#readme` div.

![page html](http://puu.sh/syYcm/2161750f83.png)

I'm on Google Chrome version 54.0.2840.99 m (Windows 10 64-bit)

**Comment by jefflembeck** [comment]
Hey @SoullessWaffle,

This is a known bug and the fix is already coming down the pipeline. Thank you for submitting, hopefully it'll be done soon!
