### ISSUE TITLE
Menu section headline links point to just "#"

### ISSUE THREAD

**Issue by mk-pmb** [npm/www#79]
(The bold items on the left under the npm logo on e.g. https://docs.npmjs.com/misc/config )

If there's really no better link target for them, please start the menus opened and only collapse them after the folding script has successfully installed its click handlers.

**Comment by aredridel** [comment]
This is actually an issue for the https://github.com/npm/docs repository, not the main website.

**Comment by mk-pmb** [comment]
Oh ok, then I'll report it there.
