### ISSUE TITLE
"npm version from git" command

### ISSUE THREAD

**Issue by nmarmon** [npm/www#80]
Hi,
It's not a issue, obviously, but I do not know exactly where to ask this. I only want to know how works the command npm version from git. I suppose that, as the command says, the packet takes the version of the git. ¿It takes the version from the github.com or from my local machine, where I have my package in local? And if the package is not binding with a git repository, ¿what does the command do?

Thanks for your answers.

**Comment by aredridel** [comment]
I suspect your question is for the CLI team (https://github.com/npm/npm).

I'm not sure quite what you're asking. The `npm version` command, though, if you've a checkout of your source code from git, it reads `package.json`, bumps the version how you specify (for example`npm version major` will increment the major number, that is, from 2.x.x to 3.0.0 or similar)

If the files are in a git repo, it will also commit and create a tag, ready to push to a remote git repository, and ready to publish to the npm registry.

(the npm registry and github don't communicate at all -- you have to publish to the registry, and push to github or your own git repository)

**Comment by aredridel** [comment]
I hope this helps!
