### ISSUE TITLE
Code blocks are very hard to read in Chrome and Safari on OS X

### ISSUE THREAD

**Issue by artcommacode** [npm/www#82]
I'm having a hard time making out comments within `<pre>` blocks due to the light weight of Courier New and  `-webkit-font-smoothing: antialiased;`. All of it's quite hard to read but comments are particularly difficult. 

Please let me know if there's anything else I can provide to help you with this issue.

<img width="757" alt="screen shot 2016-12-07 at 07 48 17" src="https://cloud.githubusercontent.com/assets/1155516/20959194/9c17948a-bc51-11e6-8064-42f4192fe707.png">

**Comment by jefflembeck** [comment]
Sorry about that,

Are you on OSX or Windows?

Is the test more legible for you if you add `-webkit-font-smoothing: subpixel-antialiased;` to the `pre` style?

**Comment by artcommacode** [comment]
I'm running 10.12.1 with Safari 10.0.1 and Chrome 54.0. 

Yes it's quite a bit more legible with `subpixel-antialiased`:

![screenshot 2016-12-07 16 36 53](https://cloud.githubusercontent.com/assets/1155516/20976792/8c3f5170-bc9b-11e6-95b3-345bd4f5cb3c.png)

**Comment by jefflembeck** [comment]
That's great info, thank you. We'll test this on Windows as well (given the way it handles subpixel rendering is different), but will likely be pushing out this change quickly.

**Comment by artcommacode** [comment]
Thanks!

**Comment by jefflembeck** [comment]
@artcommacode this change has been merged into master and hopefully will be shipped today :)

**Comment by cristianl** [comment]
The recent redesign reverted this, with `-webkit-font-smoothing: antialiased` and `-moz-osx-font-smoothing: grayscale` applied sitewide.

`antialiased` reduces contrast and font weight, so it's not ideal for readme text either – it's only ideal for light text on dark backgrounds.
