### ISSUE TITLE
Logout doesn't invalidate session

### ISSUE THREAD

**Issue by mk-pmb** [npm/www#83]
Steps to reproduce:

* Visit https://www.npmjs.com/ with Firefox version 50.0.2.
* Get a cookie named "crumb".
* Login.
* Get a cookie named "s". The top-right corner shows "Greetings," + username.
* Open some cookie editor addon, copy cookies to clipboard.
* Click the "Greetings" to open a menu, there click "Logout".
* History -> Back. The top-right corner shows "Greetings," + username.
* Refresh. The top-right corner shows "sign up or log in".
* In the cookie editor, replace all cookies with the ones from clipboard.
* Refresh. The top-right corner shows "Greetings," + username.

This can probably be used for replay attacks if you manage to decipher the SSL. (Attack vectors include personal firewalls that re-encrypt HTTPS for virus scanning.)

What should users do in case they suspect their session cookie might have leaked? (Not in my case, fortunately.)

PS: For whatever reason, the cookie seems to reset after the described procedure. When I refresh again, I'm in guest view again. I can keep the logged-in state by locking my cookies to the state I pasted from clipboard.
To verify it's not some bug with cached content for my user page, I viewed some package details pages with locked pasted cookies, and their top-right corner showed me "Greetings", too.

**Comment by aredridel** [comment]
Good catch! That should probably be invalidated indeed. I'll pass this on to our team for planning.

**Comment by ashleygwilliams** [comment]
we've filed this on our internal bug tracker. thank you SO MUCH for this super detailed bug report! it is much appreciated :) 🐬  ✨

**Comment by mk-pmb** [comment]
You're welcome. Thanks for maintaining npm!
