### ISSUE TITLE
Published new version yesterday, npmjs.com still showing previous version today

### ISSUE THREAD

**Issue by nfriedly** [npm/www#84]
Yesterday I published v0.22.0 of watson-speech (or Travis CI did on my behalf). The publish was successful, and `npm info watson-speech` shows the `latest` dist-tag as `0.22.0`.

However, https://www.npmjs.com/package/watson-speech is still showing that v0.21.0 from two weeks ago is the latest release.

Any idea what's going on?

**Comment by jefflembeck** [comment]
This normally happens when our registry follower starts lagging a little. I'll check with the registry team to see if that's the case.

**Comment by nfriedly** [comment]
OK. You can close this one if it's nothing to worry about. It just seemed odd since npm usually has lightning-fast updates.

**Comment by nfriedly** [comment]
npm looks up-to-date now, closing.
