### ISSUE TITLE
Missing Source Code

### ISSUE THREAD

**Issue by mlucool** [npm/www#86]
Hi,

There are packages that either have broken links to source or no link at all.
A few examples:
https://www.npmjs.com/package/recursive
https://www.npmjs.com/package/undefined 
https://www.npmjs.com/package/callsite (this has 3.4M downloads a month!)
https://www.npmjs.com/package/uid2 (800k downloads and not even a README)
https://www.npmjs.com/package/eyes (2.9M downloads last month)
https://www.npmjs.com/package/indexof (5.3M downloads last month)

This is a problem of both exploration and security. 

One solution is providing a way to view the source of any package. In other words, a way to view exactly what I am about to download via npm install. What are your thoughts? Do you have any other solutions?

**Comment by aredridel** [comment]
Right now, there's no way on the site to see the package as published short of downloading it and inspecting it.

However, you can use unpkg.com to see the parts: https://unpkg.com/indexof@0.0.1/ for example.

You could probably search github for the equivalent sources, and make a PR to include the repository link to their package.json, if the source is in fact hosted on github.

**Comment by mlucool** [comment]
Thanks for the response. I believe that something like unpkg.com should be included or directly linked to similar to how there is 'try it out' for all packages. Do you agree that something integrated like this would provide a higher level of safety/verifiability?

**Comment by aredridel** [comment]
I would have to study the impact and use pattern to answer that. :)

The information is there either way, but that would make it more accessible.

**Comment by mlucool** [comment]
:) Can this be re-opened and considered for enhancement?

**Comment by aredridel** [comment]
I will pass the request on to our product team, but it'll go through some iteration and decision there.

**Comment by mlucool** [comment]
Much appreciated!
