### ISSUE TITLE
"latest" version is most recently released, not the highest version

### ISSUE THREAD

**Issue by pornel** [npm/www#89]
On [package pages](https://www.npmjs.com/package/superagent) there's version information:

> 3.2.1 is the latest of 96 releases

If the latest is 3.2.1, and I `npm publish` version `1.8.9` now, it will say:

> 1.8.9 is the latest of 97 releases

which is not what I want. I don't consider a minor update to an old version to be the "latest" version of the project. 

I think this is a problem, because rollback of "latest" version on the page confuses users (I have received bug reports about this). 

When I release a maintenance patch for an old version, I do not want users to think that's *the* version they should install. The unwanted prominence of old versions discourages me from maintaining previous releases.

I'd prefer if the "latest" displayed version was the maximum version.

**Comment by JakeChampion** [comment]
"latest" is pulled from the modules "latest" dist-tag. When publishing modules, if no `--tag` is specified explicitly, "latest" is used.

If you want to point a tag at a different version you can use the `dist-tags` command. (`npm dist-tag add <pkg>@<version> [<tag>])
Here is an example where I point "latest" to the version "3.2.0" --  `npm dist-tags add example-module-name@3.2.0 latest`

If you want to publish an update which is not to be regarded as "latest", you can use a different tag, for example -- `npm publish --tag=previous`. If you didn't want the tag at all you could then remove the tag -- `npm dist-tag rm <pkg> <tag>`

**Comment by pornel** [comment]
Thanks for the workaround. I'm not quite happy with it for 2 reasons:

* Nothing about the latest version nor the latest tag is explicit. It's an implied default tag, and the site says "x is the latest of y releases", rather than "x is the most recent release with the 'latest' tag". So something I don't realise I'm using controls something else that isn't saying it depends on it.

* My primary goal for making a maintenance release is to automatically upgrade users (within semver constraints), and all my uses of tags so far were to achieve a completely opposite effect. For releasing betas I've been specifically instructed to use a `next` tag to make regular uses *not* auto-upgrade to that release, so in my mind tags are were a thing that added an extra constraint on top of semver and disabled auto-upgrades, which is not what I wanted.

**Comment by aredridel** [comment]
Yeah, that's not quite how tags work, @pornel.

Additional versions within a semver range will still be matched, regardless of tag.

Tagging something `next` instead of `latest` only affects what version comes up when one types `npm install yourpackage` and the package isn't already a dependency, or otherwise refers to it without a version.

If you want versions that don't match existing semver ranges, use prerelease versions (`-1`, etc) combined with non-`latest` tags like `next`.

**Comment by aredridel** [comment]
We do intend to make package pages reflect `latest` at some point rather than most recently published, but that requires some deeper engineering to the APIs serving the website.
