### ISSUE TITLE
can not open www.npmjs.com

### ISSUE THREAD

**Issue by lzhengms** [npm/www#90]
Whoops
Something went wrong

1481855756767:www-13-west.internal.npmjs.com:11894:iwqzmgic:27623

**Comment by aredridel** [comment]
Sorry about that! Looks like you've got a bad session cookie.

Clearing the 's' cookie (or all cookies for npmjs.com) should fix it

**Comment by lzhengms** [comment]
Thank you ！
After clearing the chorme's cookie ，it‘s ok。

**Comment by aredridel** [comment]
Sure thing! Sorry that's not more robust
