### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by ramonfritsch** [npm/www#92]
I'd like to suggest some improvement for the packages search.

Sometimes you're looking for something very popular and it's not the first result. Maybe do a 'PageRank' kind of ranking with packages, always giving more weight for popular ones.

Also, if I type a package name on the search bar and hit enter, would be nice to go right to the matching package page and not to a results page.

**Comment by aredridel** [comment]
We released an update to search! Check it out!

**Comment by ramonfritsch** [comment]
Oh, great news! Just tested it, looks great.

**Comment by aredridel** [comment]
Thanks!
