### ISSUE TITLE
Number of stars to a repo 

### ISSUE THREAD

**Issue by amitguptagwl** [npm/www#93]
If you search for [stubby](https://www.npmjs.com/search?q=stubby), you will see 54 stars in front of stubby-db. My friends gave me 2 more vote yesterday. But still the total stars are 54 only. And when you check on [nodei.co](https://nodei.co/#stubby-db) it shows only 3 star. So which is correct?

**Comment by aredridel** [comment]
I don't see any on nodei.co, but there may be some confusion here: npm stars are not the same as github repo stars. They're separate. 

Does that explain the discrepancy?

**Comment by aredridel** [comment]
No response, closing.

**Comment by amitguptagwl** [comment]
Sorry I missed the notification. 
* Yes both stars are different. 
* I got confused because npm search result was showing 54 stars. However after visiting npms.io, I got to know that it is npm score not the stars.

So yes I'm happy with your response and with new look of npm search result.
