### ISSUE TITLE
Search is still horrible

### ISSUE THREAD

**Issue by alexhultman** [npm/www#95]
I tested the new search and here are my thoughts as an author. Consider this image:

![screencapture-npmjs-search-1482658708244](https://cloud.githubusercontent.com/assets/3397140/21470571/2d0adf38-ca8f-11e6-8144-f43c0ce43c21.png)

First hit is `ws`, fair enough - one of the most downloaded and a highly starred and depended on module. You got it right this time, as compared to just "No search hits" from the last search.

Now, if we go through the rest of the list, they are all garbage projects. They have roughly speaking 0 downloads, 0 stars, 0 dependent modules, and many of them are linked to a forked github repo. Basically they are projects you would find on the last page, not the very first.

Let's take a deeper look at `uws-repack`. As the author of `uws`, a highly starred, highly depended on, highly trending, often updated, non-fork project I get very frustrated with your search results. You choose to show me some forked crap edition of my module instead of the real deal. What is even more frustrating is how you rank uws-repack as better maintained than uws, even though uws-repack hasn't been updated for 6 months.

My point is, you clearly have no feel whatsoever for what a good search should return. Clearly no quality testing has been done at all, and you more often than not serve pure garbage packages. It is not a very pleasant experience having close to 5k github stars with thousands of downloads per week and have your project outranked by some garbage module not even updated for half a year. How bad of an algorithm do you have to completely ignore every single metric of how highly regarded a project is, and instead return with pure garbage?

I hope you can take this criticism in and really try and understand how extremely dissatisfying of a search experience you have created.

**Comment by MaxArt2501** [comment]
I think this issue should be closed and possibly reopened in another form.

The title describes a very generic problem with no indication of the source. The body is merely a rant about how the new search doesn't work for your packages. This isn't the correct attitude (or tone) to help people improve their efforts. Clearly the Holyday spirit isn't working for you...

The title should reflect a more specific problem (e.g., "New search doesn't rank highly starred packages well enough") and the content should describe the issue in details, possibly giving insights about the code or statistical outcomes (comparisons with different terms and so on). This could spark a real constructive criticism that could lead to a valuable feedback from the community.

**Comment by alexhultman** [comment]
> The body is merely a rant about how the new search doesn't work for your packages.

No, it is not about *me* or *my* packages, it is an example of how bad the algorithm is *no matter who made what packages*. It is not some egoistic urge to get better promotion, I simply use my package because I know the surroundings of it and know what I'm talking about regarding it.

I don't know how I could give a better example of how broken the search is. Clearly the picture shows the problem, none of those modules are known in any way and should obviously not be ranked that high in the search result. The search is also missing some other well known modules, it is not just mine.

**Comment by MaxArt2501** [comment]
> No, it is not about *me* or *my packages*

Well then, prove it. We're talking about a search engine, it's clear that a single example hardly proves anything. Bring multiple examples, sort out the results, give hints about reproducing the problem (and no, "just use the search" isn't a valid one), ask for clarifications, point to possible solutions.

This doesn't sound to be up to par of valuable GitHub issues. Sounds more like a hot blooded rant after a quick evaluation of the new search engine.

**Comment by alexhultman** [comment]
Are you involved with NPM itself or are you just some random javascripter trolling? I don't have time or interest arguing with random javascripters, I just reported this issue to let NPM know of the search issues. I'm not going to try and explain this any further. I don't care for what random scripters think

**Comment by matmancini** [comment]
Don't drink and report issues dude, it´s not safe.

**Comment by Charlotteis** [comment]
Friends! Let's not argue.

Although this is valuable feedback, in terms of letting npm know what it is you look for in a search, you're more likely to get someone to listen to you if you don't surround valuable feedback with insults like

> you clearly have no feel whatsoever for what a good search should return
> Clearly no quality testing has been done at all

---

The new search is described here (if the partnership with npms.io is a direct "copy" so to speak): https://npms.io/about. npm now uses npms.io, meaning the team no longer use their homegrown algorithm. So it seems popularity is taken into account, but looks like it could use improvement! Sounds like npms.io would really value hearing this feedback too. I would definitely like to see the popularity of packages taken into account more, because if I'm moving fast I don't want to have to sift through too many hobby projects of no use to me, but see what the industry is using.

Have a great winter break 🌸 ⛄️

**Comment by atduarte** [comment]
For now npmjs.com doesn't show the scores from each module. You can visit https://npms.io/search?q=fast+websockets as see the scores for each module.

`uws` has a pretty bad score, since it's unstable. (https://npms.io/search?q=uws)
You can check all the data collected on `uws` here: https://api.npms.io/v2/package/uws

**Comment by bcoe** [comment]
first of all happy holidays everyone, taking a brief break from the holiday to give my two cents on this issue.

A big part of why we've been working with npms.io for search, is that we wanted to give the community the ability to have an open discussion around search results -- search is highly subjective, and we'll never get it 100% perfect, we can however have a healthy discussion around it and gradually make things "not horrible".

In the spirit of this, I've opened this ticket to open discussion about how we could improve this specific search query:

https://github.com/npms-io/npms/issues/2

Let's work together and make things awesome.

**Comment by panos1962** [comment]
Merry Christmas!
alexhultman, I'm not a heavy npm or nodejs javascripter, but I'm sure the guys who wrote npms.io are. I think you may contribute some code to make the search better.
