### ISSUE TITLE
Buggy npmjs.org/search behavior in Firefox

### ISSUE THREAD

**Issue by micnic** [npm/www#97]
Last day I received a nice email message from NPM that there is a new, improved search, I went to the page [https://www.npmjs.com/search](https://www.npmjs.com/search) and tried to search something like `npm` in the search input that is on the page, in the top search in put the first letter is added, then it is focused and the cursor is set in the first first position, before the first first letter, so I get something like `pmn` instead on `npm`.

This behavior is observed only in Firefox

![npm](https://cloud.githubusercontent.com/assets/1449826/21472659/8583cfa8-cae4-11e6-9b80-e226c3144793.gif)

**Comment by jefflembeck** [comment]
Thank you for flagging this, we’re adding it to our queue

**Comment by ashleygwilliams** [comment]
we've filed this in our issue tracker! thanks so much for including that gif- super helpful and very appreciated. 👾 🐬
