### ISSUE TITLE
Can't perform a request to the search page with the 'head' method

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [npm/www#98]
Hi,

It seems it's not possible to perform a request to the search page with the `head` method.

Try to run this code:
```js
const https = require("https");
 
var options = {
    hostname: 'www.npmjs.com',
    path: '/search?q=testcafe-browser-provider',
    method: 'head'
};
 
var req = https.request(options, (res) => {
  console.log('statusCode:', res.statusCode);
  console.log('headers:', res.headers);  
});

req.on('error', (e) => {
  console.error(e);
});

req.end();
```

It returns 503 error. It works now with `method: 'get'` only, but it was working with `head` two days ago. I suppose it's related to updating your searching. Is this a known issue?

Thanks.

**Comment by jefflembeck** [comment]
Thank you for flagging this, we’re adding it to our queue

**Comment by ashleygwilliams** [comment]
we've filed this on our internal bug tracker. thank you SO MUCH for the very detailed report. it is very appreciated 🐬 ✨ 👾
