### ISSUE TITLE
Search: ajax issue

### ISSUE THREAD

**Issue by nupamore** [npm/www#99]
The new search works like this.
If I want "foobar",

```
for "foo"
for "foob"
for "foobar"
for "fo"

wait..

for "foobar"
```

I found the same problem with my code.
So I fixed my code like this.

http://stackoverflow.com/questions/5637013/how-to-bring-ajax-search-onkeyup-with-jquery

I think that you seem to have forgotten `.abort()`.

**Comment by jefflembeck** [comment]
Thank you for flagging this, we’re adding it to our queue

**Comment by ashleygwilliams** [comment]
we've added this to our internal bug tracker! thank you for filing!
